<!DOCTYPE html>
<html lang="en"><head>
<script src="07-chi-sq-slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="07-chi-sq-slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="07-chi-sq-slides_files/libs/quarto-html/popper.min.js"></script>
<script src="07-chi-sq-slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="07-chi-sq-slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="07-chi-sq-slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="07-chi-sq-slides_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>Hypothesis Testing with Frequency Data</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="07-chi-sq-slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="07-chi-sq-slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="07-chi-sq-slides_files/libs/revealjs/dist/theme/quarto-339ab8a247387d7ad713f859dc1bbded.css">
  <link href="07-chi-sq-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="07-chi-sq-slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="07-chi-sq-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="07-chi-sq-slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Hypothesis Testing with Frequency Data</h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="ka-hua-ʻōlelo-o-ka-lā" class="slide level2">
<h2>Ka hua ʻōlelo o ka lā</h2>
<div style="text-align: center;">
<p><span class="alert">kō</span></p>
</div>
</section>
<section id="kō" class="slide level2">
<h2>Kō</h2>
<p><em>A kupuna crop, going from</em></p>
<div class="columns">
<div class="column" style="width:50%;">
<p>diversity and traditional use to…</p>
<p><img data-src="../img/ko.png"> image credit: CTAHR</p>
</div><div class="column" style="width:50%;">
<p>…exploitation and overthrow</p>
<p><img data-src="../img/cane_plantation.png"> image credit: Getty Images</p>
</div></div>
</section>
<section id="back-to-the-mms" class="slide level2">
<h2>Back to the M&amp;Ms</h2>
<p>We talked about the binomial test for the proportion of orange M&amp;Ms…but there are more than just orange and not-orange!</p>
</section>
<section id="learning-objectives" class="slide level2">
<h2>Learning Objectives</h2>
<ol type="1">
<li>Analyze a single categorical variable with &gt;2 categories using the <span class="alert"><span class="math inline">\(\chi^2\)</span> goodness-of-fit test</span></li>
</ol>
</section>
<section id="fast-facts" class="slide level2">
<h2>Fast facts</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th><strong>Binomial test of proportions</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of variables</td>
<td>1</td>
</tr>
<tr class="even">
<td>Type of data</td>
<td>categorical <strong>(2 categories)</strong></td>
</tr>
<tr class="odd">
<td>Parameter</td>
<td><span class="math inline">\(p\)</span></td>
</tr>
<tr class="even">
<td>Estimate</td>
<td><span class="math inline">\(\hat{p}\)</span></td>
</tr>
<tr class="odd">
<td>Test</td>
<td>Binomial test</td>
</tr>
<tr class="even">
<td>Sampling distribution</td>
<td>Binomial distribution</td>
</tr>
<tr class="odd">
<td>Test statistic</td>
<td>Number of “successes”</td>
</tr>
</tbody>
</table>
</section>
<section id="fast-facts-1" class="slide level2">
<h2>Fast facts</h2>
<table class="caption-top">
<colgroup>
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Binomial test of proportions</strong></th>
<th><strong><span class="math inline">\(\chi^2\)</span> goodness-of-fit test</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of variables</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Type of data</td>
<td>categorical <strong>(2 categories)</strong></td>
<td>categorical <strong>(&gt;2 categories)</strong></td>
</tr>
<tr class="odd">
<td>Parameter</td>
<td><span class="math inline">\(p\)</span></td>
<td><span class="math inline">\(\vec{p}\)</span></td>
</tr>
<tr class="even">
<td>Estimate</td>
<td><span class="math inline">\(\hat{p}\)</span></td>
<td><span class="math inline">\(\vec{\hat{p}}\)</span></td>
</tr>
<tr class="odd">
<td>Sampling distribution</td>
<td>Binomial distribution</td>
<td><span class="math inline">\(\chi^2\)</span> distribution</td>
</tr>
<tr class="even">
<td>Test statistic</td>
<td>Number of “successes”</td>
<td><span class="math inline">\(\chi^2\)</span> statistic</td>
</tr>
</tbody>
</table>
</section>
<section id="chi2-goodness-of-fit-test" class="slide level2">
<h2><span class="alert"><span class="math inline">\(\chi^2\)</span> goodness-of-fit test</span></h2>
<blockquote>
<p>The <span class="alert"><span class="math inline">\(\chi^2\)</span> goodness-of-fit test</span> compares frequency data to a probabiity model stated by the null hypothesis</p>
</blockquote>
</section>
<section id="mm-colors" class="slide level2">
<h2>M&amp;M colors</h2>
<p>According to Mars Chocolate North America, the proportion of M&amp;M colors in Milk Chocolate M&amp;Ms are:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
</tr>
</tbody>
</table>
<p>Last lecture we only cared about 2 categories: “orange” versus “not orange”</p>
<p>Now, we care about all 6 categories</p>
</section>
<section id="mm-colors-1" class="slide level2">
<h2>M&amp;M colors</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>According to the manufacturer, there are 210 candies in a 7 oz. bag. Suppose that you want to test the hypothesis that the specific bag you have is unusual. What’s a reasonable null hypothesis?</p>
</div>
</section>
<section id="mm-colors-2" class="slide level2">
<h2>M&amp;M colors</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p><span class="math inline">\(H_0\)</span>: The frequency of M&amp;Ms with each color in the bag is proportional to their proportion specified by the manufacturer</p>
<p><span class="math inline">\(H_\mathrm{A}\)</span>: The frequency of M&amp;Ms with each color in the bag is <em>not</em> proportional to their proportion specified by the manufacturer</p>
</div>
</section>
<section id="mm-colors-3" class="slide level2">
<h2>M&amp;M colors</h2>
<div class="pause-think">
<p>For a bag with 210 candies, what’s the frequency of each color expected under <span class="math inline">\(H_0\)</span>?</p>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected A</th>
<th style="text-align: center;">Expected B</th>
<th style="text-align: center;">Expected C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">50.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">42.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">33.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">29.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">27.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">27.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="mm-colors-4" class="slide level2">
<h2>M&amp;M colors</h2>
<p>The frequency of each color expected under <span class="math inline">\(H_0\)</span> is the proportion multiplied by the total number (e.g.&nbsp;<span class="math inline">\(0.24 \times 210 = 50.4\)</span>)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">50.4</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">42.0</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">33.6</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">29.4</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">210</td>
</tr>
</tbody>
</table>
</section>
<section id="mm-colors-5" class="slide level2">
<h2>M&amp;M colors</h2>
<p>Now, take a random sample</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>candies <span class="ot">&lt;-</span> <span class="fu">sample</span>(</span>
<span id="cb1-2"><a href=""></a>  <span class="at">x =</span> <span class="fu">c</span>(<span class="st">"Blue"</span>, <span class="st">"Orange"</span>, <span class="st">"Green"</span>, <span class="st">"Yellow"</span>,</span>
<span id="cb1-3"><a href=""></a>        <span class="st">"Red"</span>, <span class="st">"Brown"</span>),</span>
<span id="cb1-4"><a href=""></a>  <span class="at">size =</span> <span class="dv">210</span>,</span>
<span id="cb1-5"><a href=""></a>  <span class="at">replace =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-6"><a href=""></a>  <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.24</span>, <span class="fl">0.20</span>, <span class="fl">0.16</span>, <span class="fl">0.14</span>, <span class="fl">0.13</span>, <span class="fl">0.13</span>)</span>
<span id="cb1-7"><a href=""></a>)</span>
<span id="cb1-8"><a href=""></a></span>
<span id="cb1-9"><a href=""></a><span class="fu">table</span>(candies)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mm-colors-6" class="slide level2">
<h2>M&amp;M colors</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th>Proportion</th>
<th>Expected</th>
<th>Observed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td>0.24</td>
<td>50.4</td>
<td>43</td>
</tr>
<tr class="even">
<td>Orange</td>
<td>0.20</td>
<td>42.0</td>
<td>40</td>
</tr>
<tr class="odd">
<td>Green</td>
<td>0.16</td>
<td>33.6</td>
<td>37</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td>0.14</td>
<td>29.4</td>
<td>37</td>
</tr>
<tr class="odd">
<td>Red</td>
<td>0.13</td>
<td>27.3</td>
<td>33</td>
</tr>
<tr class="even">
<td>Brown</td>
<td>0.13</td>
<td>27.3</td>
<td>20</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>1.00</td>
<td>210</td>
<td>210</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>Which color in most over or underrepresented compared to the null hypothesis?</p>
<p>Do you think the observations are consistent with the null hypothesis?</p>
</div>
</section>
<section id="mm-colors-7" class="slide level2">
<h2>M&amp;M colors</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th>Proportion</th>
<th>Expected</th>
<th>Observed</th>
<th><span class="math inline">\((O - E)^2 / E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td>0.24</td>
<td>50.4</td>
<td>43</td>
<td>1.09</td>
</tr>
<tr class="even">
<td>Orange</td>
<td>0.20</td>
<td>42.0</td>
<td>40</td>
<td>0.1</td>
</tr>
<tr class="odd">
<td>Green</td>
<td>0.16</td>
<td>33.6</td>
<td>37</td>
<td>0.34</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td>0.14</td>
<td>29.4</td>
<td>37</td>
<td>1.96</td>
</tr>
<tr class="odd">
<td>Red</td>
<td>0.13</td>
<td>27.3</td>
<td>33</td>
<td>1.19</td>
</tr>
<tr class="even">
<td>Brown</td>
<td>0.13</td>
<td>27.3</td>
<td>20</td>
<td>1.95</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>1.00</td>
<td>210</td>
<td>210</td>
<td></td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>Yellow! Why?</p>
<p>Maybe? It’s hard to tell by eye</p>
</div>
</section>
<section id="chi2_i-measures-discrepancy-between-observed-and-expected-frequency" class="slide level2">
<h2><span class="math inline">\(\chi^2_i\)</span> measures discrepancy between observed and expected frequency</h2>
<p><span class="math inline">\(\chi^2_i\)</span> is for observation <span class="math inline">\(i\)</span></p>
<p><span class="math display">\[\chi^2_i = \frac{(Observed_i - Expected_i) ^ 2}{\mathit{Expected}_i}\]</span></p>
<p>Shorter form:</p>
<p><span class="math display">\[\chi^2_i = \frac{(O_i - E_i) ^ 2}{E_i}\]</span></p>
</section>
<section id="mm-colors-8" class="slide level2">
<h2>M&amp;M colors</h2>
<p><span class="math display">\[\chi^2_i = \frac{(O_i - E_i) ^ 2}{E_i} = \frac{(37 -29.4)^2}{29.4} = 1.96\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected</th>
<th style="text-align: center;">Observed</th>
<th style="text-align: center;"><span class="math inline">\((O - E)^2 / E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">50.4</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">1.09</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">42.0</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">0.1</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">33.6</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">0.34</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">29.4</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">1.96</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">1.19</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">1.95</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</section>
<section id="why-fraco_i---e_i-2e_i" class="slide level2">
<h2>Why <span class="math inline">\(\frac{(O_i - E_i) ^ 2}{E_i}\)</span>?</h2>
<p>Positive discrepancies have same magnitude as negative discrepancies</p>
<p><span class="math display">\[(O_i - E_i) ^ 2\]</span></p>
<p>Smaller <span class="math inline">\(E_i\)</span> have larger effect</p>
<p><span class="math display">\[\frac{1}{E_i}\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Proportion</th>
<th>Expected</th>
<th>Observed</th>
<th><span class="math inline">\((O - E)^2 / E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.990</td>
<td>990</td>
<td>950</td>
<td>1.62</td>
</tr>
<tr class="even">
<td>0.005</td>
<td>5</td>
<td>5</td>
<td>0</td>
</tr>
<tr class="odd">
<td>0.005</td>
<td>5</td>
<td>45</td>
<td>320</td>
</tr>
</tbody>
</table>
</section>
<section id="null-hypothesis-significance-testing" class="slide level2">
<h2><span class="alert">Null Hypothesis Significance Testing</span></h2>
<ol type="1">
<li>State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_\mathrm{A}\)</span></li>
<li>Calculate the test statistic</li>
<li>Generate the null distribution</li>
<li>Calculate the <span class="math inline">\(P\)</span>-value</li>
<li>Decide:
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if test statistic is <span class="math inline">\(\ge\)</span> critical value (<span class="math inline">\(P \le \alpha\)</span>)</li>
<li>Fail to reject <span class="math inline">\(H_0\)</span> if test statistic is &lt; critical value (<span class="math inline">\(P &gt; \alpha\)</span>)</li>
</ul></li>
</ol>
</section>
<section id="chi2-statistic" class="slide level2">
<h2><span class="alert"><span class="math inline">\(\chi^2\)</span> statistic</span></h2>
<blockquote>
<p>The <span class="alert"><span class="math inline">\(\chi^2\)</span></span> statistic measures the discrepency between observed frequencies from the data and expected frequencies from the null hypothesis</p>
</blockquote>
<p><span class="alert"><span class="math inline">\(\chi^2\)</span> statistic</span> is the test statistic for the <span class="alert"><span class="math inline">\(\chi^2\)</span></span> test.</p>
</section>
<section id="chi2-statistic-1" class="slide level2">
<h2><span class="alert"><span class="math inline">\(\chi^2\)</span> statistic</span></h2>
<p><span class="alert"><span class="math inline">\(\chi^2\)</span> statistic</span> is calculated by summing up all <span class="math inline">\(n\)</span> <span class="math inline">\(\chi^2_i\)</span> values</p>
<p><span class="math display">\[\chi^2 = \sum_{i=1}^n \chi^2_i= \sum_{i=1}^n \frac{(O_i - E_i) ^ 2}{E_i}\]</span></p>
</section>
<section id="mm-colors-9" class="slide level2">
<h2>M&amp;M colors</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected</th>
<th style="text-align: center;">Observed</th>
<th style="text-align: center;"><span class="math inline">\((O - E)^2 / E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">50.4</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">1.09</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">42.0</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">0.1</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">33.6</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">0.34</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">29.4</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">1.96</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">1.19</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">1.95</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">6.63</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>What is the test statistic?</p>
</div>
</section>
<section id="mm-colors-10" class="slide level2">
<h2>M&amp;M colors</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected</th>
<th style="text-align: center;">Observed</th>
<th style="text-align: center;"><span class="math inline">\((O - E)^2 / E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">50.4</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">1.09</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">42.0</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">0.1</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">33.6</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">0.34</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">29.4</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">1.96</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">1.19</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">1.95</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">6.63</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>What is the test statistic?</p>
<p><span class="math display">\[\chi^2= \sum_{i=1}^n \frac{(O_i - E_i) ^ 2}{E_i} = 6.63\]</span></p>
</div>
</section>
<section id="section" class="slide level2">
<h2>&nbsp;</h2>
<p>How often would we expect a discrepancy of <span class="math inline">\(\ge 6.63\)</span> under <span class="math inline">\(H_0\)</span>?</p>
</section>
<section id="null-hypothesis-significance-testing-1" class="slide level2">
<h2><span class="alert">Null Hypothesis Significance Testing</span></h2>
<ol type="1">
<li>State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_\mathrm{A}\)</span></li>
<li>Calculate the test statistic</li>
<li><strong>Generate the null distribution</strong></li>
<li>Calculate the <span class="math inline">\(P\)</span>-value</li>
<li>Decide:
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if test statistic is <span class="math inline">\(\ge\)</span> critical value (<span class="math inline">\(P \le \alpha\)</span>)</li>
<li>Fail to reject <span class="math inline">\(H_0\)</span> if test statistic is &lt; critical value (<span class="math inline">\(P &gt; \alpha\)</span>)</li>
</ul></li>
</ol>
</section>
<section id="chi2-distribution" class="slide level2">
<h2><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></h2>
<blockquote>
<p>The <strong><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></strong> is the sampling distribution for <span class="math inline">\(\chi^2\)</span> test statistic</p>
</blockquote>
<p><strong>Assumptions</strong></p>
<ul>
<li>None of the categories should have an expected frequency of less than 1</li>
<li>No more than 20% of the categories should have expected frequencies less than 5</li>
</ul>
</section>
<section id="checking-assumptions" class="slide level2">
<h2>Checking assumptions</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">50.4</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">42.0</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">33.6</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">29.4</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">210</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\checkmark\)</span> All Expected values &gt; 1</p>
<p><span class="math inline">\(\checkmark\)</span> Under 20% of Expected values &lt; 5</p>
</section>
<section id="checking-assumptions-1" class="slide level2">
<h2>Checking assumptions</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">9.1</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">7.6</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">6.1</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">5.3</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;"><strong>4.9</strong></td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;"><strong>4.9</strong></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">38</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\checkmark\)</span> All Expected values &gt; 1</p>
<p><span class="alert">✗</span> Under 20% of Expected values &lt; 5</p>
</section>
<section id="checking-assumptions-2" class="slide level2">
<h2>Checking assumptions</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">1.7</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">1.4</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">1.1</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;"><strong>0.9</strong></td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;"><strong>0.9</strong></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">7</td>
</tr>
</tbody>
</table>
<p><span class="alert">✗</span> All Expected values &gt; 1</p>
<p><span class="alert">✗</span> Under 20% of Expected values &lt; 5</p>
</section>
<section id="chi2-distribution-1" class="slide level2">
<h2><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></h2>
<blockquote>
<p>The <strong><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></strong> is the sampling distribution for <span class="math inline">\(\chi^2\)</span> test statistic</p>
</blockquote>
<p>Under the null hypothesis, the more categories, the larger the test statistic</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>3 categories</strong></p>
<p><span class="math display">\[
\begin{aligned}
\chi^2 &amp;= \sum_{i=1}^3 \frac{(O_i - E_i) ^ 2}{E_i} \\
&amp;= \frac{(O_1 - E_1) ^ 2}{E_1} + \frac{(O_2 - E_2) ^ 2}{E_2} + \frac{(O_3 - E_3) ^ 2}{E_3}
\end{aligned}
\]</span></p>
</div><div class="column" style="width:50%;">
<p><strong>6 categories</strong></p>
<p><span class="math display">\[
\begin{aligned}
\chi^2 = &amp;\sum_{i=1}^6 \frac{(O_i - E_i) ^ 2}{E_i} \\
= &amp;\frac{(O_1 - E_1) ^ 2}{E_1} + \frac{(O_2 - E_2) ^ 2}{E_2} + \frac{(O_3 - E_3) ^ 2}{E_3} + \\
&amp;\frac{(O_4 - E_4) ^ 2}{E_4} + \frac{(O_5 - E_5) ^ 2}{E_5} + \frac{(O_6 - E_6) ^ 2}{E_6}
\end{aligned}
\]</span></p>
</div></div>
</section>
<section id="degrees-of-freedom-for-chi2-distribution" class="slide level2">
<h2><span class="alert">Degrees of freedom for <span class="math inline">\(\chi^2\)</span> distribution</span></h2>
<blockquote>
<p>The <span class="alert">degrees of freedom</span> of a <span class="math inline">\(\chi^2\)</span> statistic capture this fact that more categories equates to larger values</p>
</blockquote>
<p><span class="math display">\[df = \mathrm{(Number~of~categories)} - 1\]</span></p>
</section>
<section id="more-degrees-of-freedom-more-likely-to-have-larger-values" class="slide level2">
<h2>More <span class="alert">degrees of freedom</span> = more likely to have larger values</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="07-chi-sq-slides_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center" style="height:80.0%" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="more-degrees-of-freedom-more-likely-to-have-larger-values-1" class="slide level2">
<h2>More <span class="alert">degrees of freedom</span> = more likely to have larger values</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Expected</th>
<th style="text-align: center;">Observed</th>
<th style="text-align: center;"><span class="math inline">\(\chi^2_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">60</td>
<td style="text-align: center;">57</td>
<td style="text-align: center;">0.150</td>
</tr>
<tr class="even">
<td style="text-align: center;">60</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">0.067</td>
</tr>
<tr class="odd">
<td style="text-align: center;">60</td>
<td style="text-align: center;">61</td>
<td style="text-align: center;">0.017</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><span class="math display">\[\mathit{df} = 3 - 1 = 2\]</span> <span class="math display">\[\chi^2 = 0.15+0.067+0.017 = 0.233\]</span></p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Expected</th>
<th style="text-align: center;">Observed</th>
<th style="text-align: center;"><span class="math inline">\(\chi^2_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">0.025</td>
</tr>
<tr class="even">
<td style="text-align: center;">40</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">1.225</td>
</tr>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">44</td>
<td style="text-align: center;">0.400</td>
</tr>
<tr class="even">
<td style="text-align: center;">40</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">0.100</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><span class="math display">\[df = 4 - 1 = 3\]</span> <span class="math display">\[\chi^2 = 0.025+1.225+0.4+0.1 = 1.75\]</span></p>
</div></div>
</section>
<section id="degrees-of-freedom-depends-on-number-of-categories-not-sample-size" class="slide level2">
<h2>Degrees of freedom depends on number of categories, not sample size</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Expected</th>
<th style="text-align: center;">Observed</th>
<th style="text-align: center;"><span class="math inline">\(\chi^2_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">60</td>
<td style="text-align: center;">57</td>
<td style="text-align: center;">0.150</td>
</tr>
<tr class="even">
<td style="text-align: center;">60</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">0.067</td>
</tr>
<tr class="odd">
<td style="text-align: center;">60</td>
<td style="text-align: center;">61</td>
<td style="text-align: center;">0.017</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><span class="math display">\[\mathit{df} = 3 - 1 = 2\]</span> <span class="math display">\[\chi^2 = 0.15+0.067+0.017 = 0.233\]</span></p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Expected</th>
<th style="text-align: center;">Observed</th>
<th style="text-align: center;"><span class="math inline">\(\chi^2_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">600</td>
<td style="text-align: center;">570</td>
<td style="text-align: center;">1.500</td>
</tr>
<tr class="even">
<td style="text-align: center;">600</td>
<td style="text-align: center;">620</td>
<td style="text-align: center;">0.667</td>
</tr>
<tr class="odd">
<td style="text-align: center;">600</td>
<td style="text-align: center;">610</td>
<td style="text-align: center;">0.167</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><span class="math display">\[\mathit{df} = 2 - 1 - 0 = 1\]</span> <span class="math display">\[\chi^2 = 1.5+0.667+0.167 = 2.333\]</span></p>
</div></div>
</section>
<section id="mm-colors-11" class="slide level2">
<h2>M&amp;M colors</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected</th>
<th style="text-align: center;">Observed</th>
<th style="text-align: center;"><span class="math inline">\((O - E)^2 / E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">50.4</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">1.09</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">42.0</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">0.1</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">33.6</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">0.34</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">29.4</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">1.96</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">1.19</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">1.95</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">6.63</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>How many degrees of freedom should we use for these data?</p>
</div>
</section>
<section id="mm-colors-12" class="slide level2">
<h2>M&amp;M colors</h2>
<div class="pause-think">
<p><span class="math display">\[df =  \mathrm{(Number~of~categories)} - 1 \]</span></p>
<p><span class="math display">\[\mathit{df} = 6 - 1 = 5\]</span></p>
</div>
</section>
<section id="chi_52-distribution-graphically" class="slide level2">
<h2><span class="math inline">\(\chi_5^2\)</span> distribution (graphically)</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="07-chi-sq-slides_files/figure-revealjs/unnamed-chunk-9-1.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="chi_mathitdf2-distribution" class="slide level2">
<h2><span class="math inline">\(\chi_\mathit{df}^2\)</span> distribution</h2>
<p>Why is the <span class="math inline">\(\chi_\mathit{df}^2\)</span> distribution <em>continuous</em> even though we are working with a categorical variable with discrete frequencies?</p>
<p>Because <span class="math inline">\(\chi_\mathit{df}^2\)</span> is an approximation of the “true” sampling distribution</p>
</section>
<section id="chi_52-distribution-with-test-statistic" class="slide level2">
<h2><span class="math inline">\(\chi_5^2\)</span> distribution with test statistic</h2>
<p>Recall we calculated for the M&amp;Ms: <span class="math inline">\(\chi^2 = 6.63\)</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="07-chi-sq-slides_files/figure-revealjs/unnamed-chunk-10-1.png" class="quarto-figure quarto-figure-center" style="width:95.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="chi_mathitdf2-distribution-1" class="slide level2">
<h2><span class="math inline">\(\chi_\mathit{df}^2\)</span> distribution</h2>
<p><span class="math inline">\(\chi_\mathit{df}^2\)</span> distribution</p>
<p>The <span class="math inline">\(P\)</span>-value will be the area to the right of test statistic.</p>
<p>So this is a <span class="alert">one-tailed</span> test. Why?</p>
<p>We are only interested if the discrepancy between <em>Expected</em> and <em>Observed</em> is <strong>more</strong> than we expect under <span class="math inline">\(H_0\)</span></p>
<p><span class="math display">\[\frac{(O_i - E_i)^2}{E_i}\]</span></p>
<p>Higher test statistics = more discrepancy between <em>Expected</em> and <em>Observed</em></p>
</section>
<section id="null-hypothesis-significance-testing-2" class="slide level2">
<h2><span class="alert">Null Hypothesis Significance Testing</span></h2>
<ol type="1">
<li>State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_\mathrm{A}\)</span></li>
<li>Calculate the test statistic</li>
<li>Generate the null distribution</li>
<li><em>Find the critical value at a specified <span class="math inline">\(\alpha\)</span></em></li>
<li>Calculate the <span class="math inline">\(P\)</span>-value</li>
<li>Decide:
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if test statistic is <span class="math inline">\(\ge\)</span> critical value (<span class="math inline">\(P \le \alpha\)</span>)</li>
<li>Fail to reject <span class="math inline">\(H_0\)</span> if test statistic is &lt; critical value (<span class="math inline">\(P &gt; \alpha\)</span>)</li>
</ul></li>
</ol>
</section>
<section id="critical-value" class="slide level2">
<h2><span class="alert">Critical value</span></h2>
<blockquote>
<p>A <span class="alert">critical value</span> is the value of a test statistic that marks the boundary of a specified area in the tail (or tails) of the sampling distribution under <span class="math inline">\(H_0\)</span></p>
</blockquote>
</section>
<section id="critical-value-1" class="slide level2">
<h2><span class="alert">Critical value</span></h2>
<p>You <em>can</em> look up critical values in a table if you’re a dinosaur</p>
<p><span class="math inline">\(\alpha = 0.05\)</span>, <span class="math inline">\(\mathit{df} = 5\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="fu">qchisq</span>(<span class="fl">0.05</span>,</span>
<span id="cb2-2"><a href=""></a>       <span class="at">df =</span> <span class="dv">5</span>,</span>
<span id="cb2-3"><a href=""></a>       <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.0705</code></pre>
</div>
</div>
</section>
<section id="chi_52-distribution-with-critical-value" class="slide level2">
<h2><span class="math inline">\(\chi_5^2\)</span> distribution with critical value</h2>
<p><span class="math inline">\(\alpha = 0.05\)</span>, <span class="math inline">\(\mathit{df} = 5\)</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="07-chi-sq-slides_files/figure-revealjs/unnamed-chunk-12-1.png" class="quarto-figure quarto-figure-center" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="chi_52-distribution-with-test-statistic-and-critical-value" class="slide level2">
<h2><span class="math inline">\(\chi_5^2\)</span> distribution with test statistic and critical value</h2>
<p><span class="math inline">\(\alpha = 0.05\)</span>, <span class="math inline">\(\mathit{df} = 5\)</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="07-chi-sq-slides_files/figure-revealjs/unnamed-chunk-13-1.png" class="quarto-figure quarto-figure-center" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="null-hypothesis-significance-testing-3" class="slide level2">
<h2><span class="alert">Null Hypothesis Significance Testing</span></h2>
<ol type="1">
<li>State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_\mathrm{A}\)</span></li>
<li>Calculate the test statistic</li>
<li>Generate the null distribution</li>
<li>Find the critical value at a specified <span class="math inline">\(\alpha\)</span></li>
<li><em>Find the <span class="math inline">\(P\)</span>-value</em></li>
<li>Decide:
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if test statistic is <span class="math inline">\(\ge\)</span> critical value (<span class="math inline">\(P \le \alpha\)</span>)</li>
<li>Fail to reject <span class="math inline">\(H_0\)</span> if test statistic is &lt; critical value (<span class="math inline">\(P &gt; \alpha\)</span>)</li>
</ul></li>
</ol>
</section>
<section id="p-value" class="slide level2">
<h2><span class="alert"><span class="math inline">\(P\)</span>-value</span></h2>
<p><span class="math inline">\(\chi^2~\text{statistic} = 6.632544\)</span>, <span class="math inline">\(\mathit{df} = 5\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="fu">pchisq</span>(<span class="at">q =</span> <span class="fl">6.632544</span>,</span>
<span id="cb4-2"><a href=""></a>       <span class="at">df =</span> <span class="dv">5</span>,</span>
<span id="cb4-3"><a href=""></a>       <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2494337</code></pre>
</div>
</div>
<p><em>(Note: if you were alive in the Pleistocene you might look up a P-value and/or critical value in a table in the back of your stats book)</em></p>
</section>
<section id="null-hypothesis-significance-testing-4" class="slide level2">
<h2><span class="alert">Null Hypothesis Significance Testing</span></h2>
<ol type="1">
<li>State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_\mathrm{A}\)</span></li>
<li>Calculate the test statistic</li>
<li>Generate the null distribution</li>
<li>Find the critical value at a specified <span class="math inline">\(\alpha\)</span></li>
<li>Find the <span class="math inline">\(P\)</span>-value</li>
<li><em>Decide:</em>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if test statistic is <span class="math inline">\(\ge\)</span> critical value (<span class="math inline">\(P \le \alpha\)</span>)</li>
<li>Fail to reject <span class="math inline">\(H_0\)</span> if test statistic is &lt; critical value (<span class="math inline">\(P &gt; \alpha\)</span>)</li>
</ul></li>
</ol>
</section>
<section id="decide" class="slide level2">
<h2>Decide</h2>
<p><span class="math inline">\(\alpha = 0.05\)</span>, <span class="math inline">\(P = 0.25\)</span></p>
<p><span class="math display">\[0.25 &gt; 0.05\]</span></p>
<p>We fail to reject <span class="math inline">\(H_0\)</span></p>
<p>We do not have sufficient evidence to say that the frequency of candy colors differs significantly from what we would expect based on the manufacturer’s information</p>
</section>
<section id="the-quick-way-in-r" class="slide level2">
<h2>The quick way in <em>R</em></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a><span class="fu">chisq.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">43</span>, <span class="dv">40</span>, <span class="dv">37</span>, <span class="dv">37</span>, <span class="dv">33</span>, <span class="dv">20</span>),</span>
<span id="cb6-2"><a href=""></a>           <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.24</span>, <span class="fl">0.20</span>, <span class="fl">0.16</span>, <span class="fl">0.14</span>, <span class="fl">0.13</span>, <span class="fl">0.13</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  c(43, 40, 37, 37, 33, 20)
X-squared = 6.6325, df = 5, p-value = 0.2494</code></pre>
</div>
</div>
</section>
<section id="summary" class="slide level2">
<h2>Summary</h2>
<p>The <span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span> describes the sampling distribution of the discrepancy between expected and observed frequencies</p>
<p>It is an approximate test, but works well when sample size are large that assumptions are met</p>
</section>
<section>
<section id="break" class="title-slide slide level1 center">
<h1>Break!</h1>

</section>
<section id="ka-hua-ʻōlelo-o-ka-lā-1" class="slide level2">
<h2>Ka hua ʻōlelo o ka lā</h2>
<div style="text-align: center;">
<p><span class="alert">hānau</span></p>
</div>
</section>
<section id="learning-objectives-1" class="slide level2">
<h2>Learning Objectives</h2>
<ol type="1">
<li>Analyze two or more categorical variable with <span class="math inline">\(\ge 2\)</span> categories using the <span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span> and <span class="alert">contingency analysis</span></li>
</ol>
</section>
<section id="review-of-chi2-goodness-of-fit-test" class="slide level2">
<h2>Review of <span class="math inline">\(\chi^2\)</span> goodness of fit test</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th><strong><span class="math inline">\(\chi^2\)</span> goodness-of-fit test</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of variables</td>
<td>1</td>
</tr>
<tr class="even">
<td>Type of data</td>
<td>categorical <strong>(&gt;2 categories)</strong></td>
</tr>
<tr class="odd">
<td>Parameter</td>
<td><span class="math inline">\(\vec{p}\)</span></td>
</tr>
<tr class="even">
<td>Estimate</td>
<td><span class="math inline">\(\vec{\hat{p}}\)</span></td>
</tr>
<tr class="odd">
<td>Sampling distribution</td>
<td><span class="math inline">\(\chi^2\)</span> distribution</td>
</tr>
<tr class="even">
<td>Test statistic</td>
<td><span class="math inline">\(\chi^2\)</span> statistic</td>
</tr>
</tbody>
</table>
</section>
<section id="chi2-goodness-of-fit-test-1" class="slide level2">
<h2><span class="alert"><span class="math inline">\(\chi^2\)</span> goodness-of-fit test</span></h2>
<blockquote>
<p>The <span class="alert"><span class="math inline">\(\chi^2\)</span> goodness-of-fit test</span> compares frequency data to a probability model stated by the null hypothesis</p>
</blockquote>
</section>
<section id="mm-colors-13" class="slide level2">
<h2>M&amp;M colors</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th>Proportion</th>
<th>Expected</th>
<th>Observed</th>
<th><span class="math inline">\((O - E)^2 / E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td>0.24</td>
<td>50.4</td>
<td>43</td>
<td>1.09</td>
</tr>
<tr class="even">
<td>Orange</td>
<td>0.20</td>
<td>42.0</td>
<td>40</td>
<td>0.1</td>
</tr>
<tr class="odd">
<td>Green</td>
<td>0.16</td>
<td>33.6</td>
<td>37</td>
<td>0.34</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td>0.14</td>
<td>29.4</td>
<td>37</td>
<td>1.96</td>
</tr>
<tr class="odd">
<td>Red</td>
<td>0.13</td>
<td>27.3</td>
<td>33</td>
<td>1.19</td>
</tr>
<tr class="even">
<td>Brown</td>
<td>0.13</td>
<td>27.3</td>
<td>20</td>
<td>1.95</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>1.00</td>
<td>210</td>
<td>210</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\chi^2_i = \frac{(Observed_i - Expected_i) ^ 2}{\mathit{Expected}_i}\]</span></p>
<p><span class="math inline">\(\chi^2_i\)</span> measures discrepancy between observed and expected frequency</p>
</section>
<section id="chi2-statistic-2" class="slide level2">
<h2><span class="alert"><span class="math inline">\(\chi^2\)</span> statistic</span></h2>
<blockquote>
<p>The <span class="alert"><span class="math inline">\(\chi^2\)</span></span> statistic measures the discrepency between observed frequencies from the data and expected frequencies from the null hypothesis</p>
</blockquote>
<p><span class="alert"><span class="math inline">\(\chi^2\)</span> statistic</span> is calculated by summing up all <span class="math inline">\(n\)</span> <span class="math inline">\(\chi^2_i\)</span> values</p>
<p><span class="math display">\[\chi^2 = \sum_{i=1}^n \chi^2_i= \sum_{i=1}^n \frac{(O_i - E_i) ^ 2}{E_i}\]</span></p>
</section>
<section id="mm-colors-14" class="slide level2">
<h2>M&amp;M colors</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected</th>
<th style="text-align: center;">Observed</th>
<th style="text-align: center;"><span class="math inline">\((O - E)^2 / E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">50.4</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">1.09</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">42.0</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">0.1</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">33.6</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">0.34</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">29.4</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">1.96</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">1.19</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">1.95</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">6.63</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>What is the test statistic?</p>
<p><span class="math display">\[\chi^2= \sum_{i=1}^n \frac{(O_i - E_i) ^ 2}{E_i} = 6.63\]</span></p>
</div>
</section>
<section id="section-1" class="slide level2">
<h2>&nbsp;</h2>
<p>How often would we expect a discrepancy of <span class="math inline">\(\ge 6.63\)</span> under <span class="math inline">\(H_0\)</span>?</p>
</section>
<section id="null-hypothesis-significance-testing-5" class="slide level2">
<h2><span class="alert">Null Hypothesis Significance Testing</span></h2>
<ol type="1">
<li>State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_\mathrm{A}\)</span></li>
<li>Calculate the test statistic</li>
<li><strong>Generate the null distribution</strong></li>
<li>Calculate the <span class="math inline">\(P\)</span>-value</li>
<li>Decide:
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if test statistic is <span class="math inline">\(\ge\)</span> critical value (<span class="math inline">\(P \le \alpha\)</span>)</li>
<li>Fail to reject <span class="math inline">\(H_0\)</span> if test statistic is &lt; critical value (<span class="math inline">\(P &gt; \alpha\)</span>)</li>
</ul></li>
</ol>
</section>
<section id="chi2-distribution-2" class="slide level2">
<h2><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></h2>
<blockquote>
<p>The <strong><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></strong> is the sampling distribution for <span class="math inline">\(\chi^2\)</span> test statistic</p>
</blockquote>
<p><strong>Assumptions</strong></p>
<ul>
<li>None of the categories should have an expected frequency of less than 1</li>
<li>No more than 20% of the categories should have expected frequencies less than 5</li>
</ul>
</section>
<section id="chi2-distribution-3" class="slide level2">
<h2><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></h2>
<blockquote>
<p>The <strong><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></strong> is the sampling distribution for <span class="math inline">\(\chi^2\)</span> test statistic</p>
</blockquote>
<p>Under the null hypothesis, the more categories, the larger the test statistic</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>3 categories</strong></p>
<p><span class="math display">\[
\begin{aligned}
\chi^2 &amp;= \sum_{i=1}^3 \frac{(O_i - E_i) ^ 2}{E_i} \\
&amp;= \frac{(O_1 - E_1) ^ 2}{E_1} + \frac{(O_2 - E_2) ^ 2}{E_2} + \frac{(O_3 - E_3) ^ 2}{E_3}
\end{aligned}
\]</span></p>
</div><div class="column" style="width:50%;">
<p><strong>6 categories</strong></p>
<p><span class="math display">\[
\begin{aligned}
\chi^2 = &amp;\sum_{i=1}^3 \frac{(O_i - E_i) ^ 2}{E_i} \\
= &amp;\frac{(O_1 - E_1) ^ 2}{E_1} + \frac{(O_2 - E_2) ^ 2}{E_2} + \frac{(O_3 - E_3) ^ 2}{E_3} + \\
&amp;\frac{(O_4 - E_4) ^ 2}{E_4} + \frac{(O_5 - E_5) ^ 2}{E_5} + \frac{(O_6 - E_6) ^ 2}{E_6}
\end{aligned}
\]</span></p>
</div></div>
</section>
<section id="degrees-of-freedom-for-chi2-distribution-1" class="slide level2">
<h2><span class="alert">Degrees of freedom for <span class="math inline">\(\chi^2\)</span> distribution</span></h2>
<blockquote>
<p>The <span class="alert">degrees of freedom</span> of a <span class="math inline">\(\chi^2\)</span> statistic capture this fact that more categories equates to larger values</p>
</blockquote>
<p><span class="math display">\[df = \mathrm{(Number~of~categories)} - 1\]</span></p>
</section>
<section id="mm-colors-15" class="slide level2">
<h2>M&amp;M colors</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Color</th>
<th style="text-align: center;">Proportion</th>
<th style="text-align: center;">Expected</th>
<th style="text-align: center;">Observed</th>
<th style="text-align: center;"><span class="math inline">\((O - E)^2 / E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blue</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">50.4</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">1.09</td>
</tr>
<tr class="even">
<td>Orange</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">42.0</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">0.1</td>
</tr>
<tr class="odd">
<td>Green</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">33.6</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">0.34</td>
</tr>
<tr class="even">
<td>Yellow</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">29.4</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">1.96</td>
</tr>
<tr class="odd">
<td>Red</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">1.19</td>
</tr>
<tr class="even">
<td>Brown</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">27.3</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">1.95</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">210</td>
<td style="text-align: center;">6.63</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[df =  \mathrm{(Number~of~categories)} - 1 \]</span></p>
<p><span class="math display">\[\mathit{df} = 6 - 1 = 5\]</span></p>
</section>
<section id="chi_52-distribution-with-test-statistic-1" class="slide level2">
<h2><span class="math inline">\(\chi_5^2\)</span> distribution with test statistic</h2>
<p>Recall we calculated for the M&amp;Ms: <span class="math inline">\(\chi^2 = 6.63\)</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="07-chi-sq-slides_files/figure-revealjs/unnamed-chunk-18-1.png" class="quarto-figure quarto-figure-center" style="width:95.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="chi_mathitdf2-distribution-2" class="slide level2">
<h2><span class="math inline">\(\chi_\mathit{df}^2\)</span> distribution</h2>
<p>The <span class="math inline">\(P\)</span>-value will be the area to the right of test statistic.</p>
<p>So this is a <span class="alert">one-tailed</span> test. Why?</p>
<p>We are only interested if the discrepancy between <em>Expected</em> and <em>Observed</em> is <strong>more</strong> than we expect under <span class="math inline">\(H_0\)</span></p>
<p><span class="math display">\[\frac{(O_i - E_i)^2}{E_i}\]</span></p>
<p>Higher test statistics = more discrepancy between <em>Expected</em> and <em>Observed</em></p>
</section>
<section id="p-value-1" class="slide level2">
<h2><span class="alert"><span class="math inline">\(P\)</span>-value</span></h2>
<p><span class="math inline">\(\chi^2~\text{statistic} = 6.632544\)</span>, <span class="math inline">\(\mathit{df} = 5\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a><span class="fu">pchisq</span>(<span class="at">q =</span> <span class="fl">6.632544</span>,</span>
<span id="cb8-2"><a href=""></a>       <span class="at">df =</span> <span class="dv">5</span>,</span>
<span id="cb8-3"><a href=""></a>       <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2494337</code></pre>
</div>
</div>
</section>
<section id="contingency-analysis-from-1-variable-to-2" class="slide level2">
<h2>Contingency analysis: from 1 variable to <strong>2</strong>!</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong><span class="math inline">\(\chi^2\)</span> goodness-of-fit test</strong></th>
<th><strong>Contingency test</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of variables</td>
<td>1</td>
<td><strong>2</strong></td>
</tr>
<tr class="even">
<td>Type of data</td>
<td>categorical</td>
<td>categorical</td>
</tr>
<tr class="odd">
<td>Parameter</td>
<td><span class="math inline">\(\vec{p}\)</span></td>
<td><em>???</em></td>
</tr>
<tr class="even">
<td>Estimate</td>
<td><span class="math inline">\(\vec{\hat{p}}\)</span></td>
<td><em>???</em></td>
</tr>
<tr class="odd">
<td>Sampling distribution</td>
<td><span class="math inline">\(\chi^2\)</span> distribution</td>
<td><span class="math inline">\(\chi^2\)</span> distribution</td>
</tr>
<tr class="even">
<td>Test statistic</td>
<td><span class="math inline">\(\chi^2\)</span> statistic</td>
<td><span class="math inline">\(\chi^2\)</span> statistic</td>
</tr>
</tbody>
</table>
</section>
<section id="contingency-analysis-from-1-variable-to-2-1" class="slide level2">
<h2>Contingency analysis: from 1 variable to <strong>2</strong>!</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div style="text-align: center;">
<p><span class="math inline">\(\chi^2\)</span> goodness of fit</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Category</th>
<th style="text-align: center;">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">category 1</td>
<td style="text-align: center;"><span class="math inline">\(O_1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">category 2</td>
<td style="text-align: center;"><span class="math inline">\(O_2\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">category 3</td>
<td style="text-align: center;"><span class="math inline">\(O_3\)</span></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<div style="text-align: center;">
<p>Contingency Analysis</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">category A</th>
<th style="text-align: center;">category B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">category 1</td>
<td style="text-align: center;"><span class="math inline">\(O_{1A}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{1B}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">category 2</td>
<td style="text-align: center;"><span class="math inline">\(O_{2A}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{2B}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">category 3</td>
<td style="text-align: center;"><span class="math inline">\(O_{3A}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{3B}\)</span></td>
</tr>
</tbody>
</table>
</div></div>
</section>
<section id="contingency-analysis-this-is-a-contigency-table" class="slide level2">
<h2>Contingency analysis: this is a <span class="alert">contigency table</span></h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>We will put the <span class="alert">response variable</span> across rows</p>
</div><div class="column" style="width:50%;">
<p>We will put the <span class="alert">explanatory variable</span> across columns</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">category A</th>
<th style="text-align: center;">category B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">category 1</td>
<td style="text-align: center;"><span class="math inline">\(O_{1A}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{1B}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">category 2</td>
<td style="text-align: center;"><span class="math inline">\(O_{2A}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{2B}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">category 3</td>
<td style="text-align: center;"><span class="math inline">\(O_{3A}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(O_{3B}\)</span></td>
</tr>
</tbody>
</table>
</div></div>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: left;">non-English speaker</th>
<th style="text-align: left;">English speaker</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: left;">127</td>
<td style="text-align: left;">934</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: left;">1022</td>
<td style="text-align: left;">9336</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Are non-English speakers more likely to undergo C-section in their first delivery?</p>
</blockquote>
<p>data from: Sentell et al.&nbsp;(2016). Maternal language and adverse birth outcomes in a statewide analysis. <em>Women &amp; Health</em></p>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-1" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<p><strong>Context</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../img/csection-fridays.png" class="quarto-figure quarto-figure-center" style="width:75.0%"></p>
</figure>
</div>
<p>C-section rates have increased due to physician choices that disregard maternal/parental choice and health for parent and baby</p>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-2" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<p><strong>Context</strong></p>
<p><img data-src="../img/healthcare_women.png"></p>
<p>There’s a breakdown in trust, ethics, and real healthcare</p>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-3" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<p><strong>Context</strong></p>
<p><img data-src="../img/healthcare_race.png"></p>
<p>The breakdown intersects with race</p>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-4" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<p><strong>Context</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../img/healthcare_trans.png" class="quarto-figure quarto-figure-center" style="width:70.0%"></p>
</figure>
</div>
<p>The breakdown intersects with gender identity</p>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-5" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English speaker</th>
<th style="text-align: center;">English speaker</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: center;">127</td>
<td style="text-align: center;">934</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: center;">1022</td>
<td style="text-align: center;">9336</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Are non-English speakers more likely to undergo C-section in their first delivery?</p>
</blockquote>
</section>
<section id="null-hypothesis-significance-testing-6" class="slide level2">
<h2><span class="alert">Null Hypothesis Significance Testing</span></h2>
<ol type="1">
<li>State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_\mathrm{A}\)</span></li>
<li>Calculate the test statistic</li>
<li>Generate the null distribution</li>
<li>Calculate the <span class="math inline">\(P\)</span>-value</li>
<li>Decide:
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if test statistic is <span class="math inline">\(\ge\)</span> critical value (<span class="math inline">\(P \le \alpha\)</span>)</li>
<li>Fail to reject <span class="math inline">\(H_0\)</span> if test statistic is &lt; critical value (<span class="math inline">\(P &gt; \alpha\)</span>)</li>
</ul></li>
</ol>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-6" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<p>Contingency analysis uses the <span class="math inline">\(\chi^2\)</span> test statistic, so we need <em>observed</em> and <em>expected</em> frequencies</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: center;">127</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">934</td>
<td style="text-align: center;">??</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: center;">1022</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">9336</td>
<td style="text-align: center;">??</td>
</tr>
</tbody>
</table>
</section>
<section id="example-simpler-numbers" class="slide level2">
<h2>Example: simpler numbers</h2>
<p>Contingency analysis uses the <span class="math inline">\(\chi^2\)</span> test statistic, so we need <em>observed</em> and <em>expected</em> frequencies</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">??</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">??</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>What should the expected frequencies be?</p>
</div>
</section>
<section id="example-simpler-numbers-1" class="slide level2">
<h2>Example: simpler numbers</h2>
<p>Contingency analysis uses the <span class="math inline">\(\chi^2\)</span> test statistic, so we need <em>observed</em> and <em>expected</em> frequencies</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">10</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>Is that right?…No…</p>
</div>
</section>
<section id="example-simpler-numbers-2" class="slide level2">
<h2>Example: simpler numbers</h2>
<p>Contingency analysis uses the <span class="math inline">\(\chi^2\)</span> test statistic, so we need <em>observed</em> and <em>expected</em> frequencies</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">??</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">??</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>Expected frequencies come from the null hypothesis. What is the null hypothesis?</p>
</div>
</section>
<section id="example-simpler-numbers-3" class="slide level2">
<h2>Example: simpler numbers</h2>
<p>Contingency analysis uses the <span class="math inline">\(\chi^2\)</span> test statistic, so we need <em>observed</em> and <em>expected</em> frequencies</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">??</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">??</td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>Expected frequencies come from the null hypothesis. What is the null hypothesis? <strong>equal proportions across explanatory groups</strong></p>
</div>
</section>
<section id="example-simpler-numbers-4" class="slide level2">
<h2>Example: simpler numbers</h2>
<p>Contingency analysis uses the <span class="math inline">\(\chi^2\)</span> test statistic, so we need <em>observed</em> and <em>expected</em> frequencies</p>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;"><strong>Totals</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary C-section</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;"><strong>3</strong></td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;"><strong>21</strong></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Totals</strong></td>
<td style="text-align: center;"><strong>6</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>18</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>24</strong></td>
</tr>
</tbody>
</table>
<div class="pause-think">
<p>Expected frequencies come from the null hypothesis. What is the null hypothesis? <strong>equal proportions across explanatory groups</strong></p>
</div>
</section>
<section id="example-simpler-numbers-5" class="slide level2">
<h2>Example: simpler numbers</h2>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;"><strong>Totals</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary C-section</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;"><strong>3</strong></td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">??</td>
<td style="text-align: center;"><strong>21</strong></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Totals</strong></td>
<td style="text-align: center;"><strong>6</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>18</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>24</strong></td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\hat{\text{Pr}}(\text{non-English speaker}) = \frac{1}{4}\)</span> <span class="math inline">\(\hat{\text{Pr}}(\text{English speaker}) = \frac{3}{4}\)</span></p>
<p>So expected frequencies assuming equal proportions across groups would be</p>
<p><span class="math inline">\(E_{\text{C-section, non-English}} = \frac{1}{4} \times 3 = \frac{3}{4}\)</span> <span class="math inline">\(E_{\text{C-section, English}} = \frac{3}{4} \times 3 = 2\frac{1}{4}\)</span> <span class="math inline">\(E_{\text{VB, non-English}} = \frac{1}{4} \times 21 = 5 \frac{1}{4}\)</span> <span class="math inline">\(E_{\text{C-section, English}} = \frac{3}{4} \times 21 = 15 \frac{3}{4}\)</span></p>
</section>
<section id="example-simpler-numbers-6" class="slide level2">
<h2>Example: simpler numbers</h2>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;"><strong>Totals</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary C-section</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(\frac{3}{4}\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(2\frac{1}{4}\)</span></td>
<td style="text-align: center;"><strong>3</strong></td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;"><span class="math inline">\(5 \frac{1}{4}\)</span></td>
<td style="text-align: center;">16</td>
<td style="text-align: center;"><span class="math inline">\(15 \frac{3}{4}\)</span></td>
<td style="text-align: center;"><strong>21</strong></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Totals</strong></td>
<td style="text-align: center;"><strong>6</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>18</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>24</strong></td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\hat{\text{Pr}}(\text{non-English speaker}) = \frac{1}{4}\)</span> <span class="math inline">\(\hat{\text{Pr}}(\text{English speaker}) = \frac{3}{4}\)</span></p>
<p>So expected frequencies assuming equal proportions across groups would be</p>
<p><span class="math inline">\(E_{\text{C-section, non-English}} = \frac{1}{4} \times 3 = \frac{3}{4}\)</span> <span class="math inline">\(E_{\text{C-section, English}} = \frac{3}{4} \times 3 = 2\frac{1}{4}\)</span> <span class="math inline">\(E_{\text{VB, non-English}} = \frac{1}{4} \times 21 = 5 \frac{1}{4}\)</span> <span class="math inline">\(E_{\text{C-section, English}} = \frac{3}{4} \times 21 = 15 \frac{3}{4}\)</span></p>
</section>
<section id="example-simpler-numbers-7" class="slide level2">
<h2>Example: simpler numbers</h2>
<p><span class="math inline">\(\chi^2\)</span> test statistic is</p>
<p><span class="math display">\[\chi^2 = \sum_{i=1}^n \frac{(O_i - E_i) ^ 2}{E_i}\]</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;"><strong>Totals</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary C-section</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(\frac{3}{4}\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(2\frac{1}{4}\)</span></td>
<td style="text-align: center;"><strong>3</strong></td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;"><span class="math inline">\(5 \frac{1}{4}\)</span></td>
<td style="text-align: center;">16</td>
<td style="text-align: center;"><span class="math inline">\(15 \frac{3}{4}\)</span></td>
<td style="text-align: center;"><strong>21</strong></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Totals</strong></td>
<td style="text-align: center;"><strong>6</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>18</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>24</strong></td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\chi^2 = \frac{0.25^2}{0.75} + \frac{-0.25^2}{5.25} + \frac{-0.25^2}{2.25} + \frac{0.25^2}{15.75}\)</span></p>
<p><span class="math inline">\(\chi^2 = 0.127\)</span></p>
</section>
<section id="example-simpler-numbers-8" class="slide level2">
<h2>Example: simpler numbers</h2>
<p><span class="math inline">\(\chi^2\)</span> test statistic is <span class="math inline">\(\chi^2 = 0.127\)</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;"><strong>Totals</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary C-section</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(\frac{3}{4}\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(2\frac{1}{4}\)</span></td>
<td style="text-align: center;"><strong>3</strong></td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;"><span class="math inline">\(5 \frac{1}{4}\)</span></td>
<td style="text-align: center;">16</td>
<td style="text-align: center;"><span class="math inline">\(15 \frac{3}{4}\)</span></td>
<td style="text-align: center;"><strong>21</strong></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Totals</strong></td>
<td style="text-align: center;"><strong>6</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>18</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>24</strong></td>
</tr>
</tbody>
</table>
<p>What about degrees of freedom?</p>
<p>For a contingency test, <span class="math inline">\(df = (\text{number of rows} - 1) \times (\text{number of columns} - 1)\)</span></p>
<p><span class="math inline">\(df = (2 - 1) \times (2 - 1)\)</span></p>
<p><span class="math inline">\(df = 1\)</span></p>
</section>
<section id="example-simpler-numbers-9" class="slide level2">
<h2>Example: simpler numbers</h2>
<p><strong>Let’s run our null hypothesis test</strong></p>
<p><span class="math inline">\(H_0\)</span>: there is no difference in the proportions across explanatory groups</p>
<p><span class="math inline">\(H_A\)</span>: there <em>is</em> a difference in the proportions across explanatory groups</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a>chi2_test_stat <span class="ot">&lt;-</span> <span class="fl">0.127</span></span>
<span id="cb10-2"><a href=""></a>df <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb10-3"><a href=""></a></span>
<span id="cb10-4"><a href=""></a><span class="fu">pchisq</span>(chi2_test_stat, df, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.721563</code></pre>
</div>
</div>
<p>We fail to reject the null</p>
</section>
<section id="example-simpler-numbers-10" class="slide level2">
<h2>Example: simpler numbers</h2>
<p><strong>Let’s run our null hypothesis test</strong></p>
<p><span class="math inline">\(H_0\)</span>: there is no difference in the proportions across explanatory groups</p>
<p><span class="math inline">\(H_A\)</span>: there <em>is</em> a difference in the proportions across explanatory groups</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a>dat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">16</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb12-2"><a href=""></a>dat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    1    2
[2,]    5   16</code></pre>
</div>
</div>
</section>
<section id="example-simpler-numbers-11" class="slide level2">
<h2>Example: simpler numbers</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a><span class="co"># simpler to use the built-in chi-squared test function</span></span>
<span id="cb14-2"><a href=""></a><span class="fu">chisq.test</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(dat): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  dat
X-squared = 0, df = 1, p-value = 1</code></pre>
</div>
</div>
<p>And this tells us we shouldn’t be using <span class="math inline">\(\chi^2\)</span> because our sample size is too small!</p>
</section>
<section id="example-simpler-numbers-12" class="slide level2">
<h2>Example: simpler numbers</h2>
<p><strong>Sure enough we had an expected frequency less than 1!!!</strong></p>
<p><strong>Also half our expected frequencies are under 5</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">non-English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(O\)</span></th>
<th style="text-align: center;">English <span class="math inline">\(E\)</span></th>
<th style="text-align: center;"><strong>Totals</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary C-section</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"><span class="math inline">\(\frac{3}{4}\)</span></td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(2\frac{1}{4}\)</span></td>
<td style="text-align: center;"><strong>3</strong></td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;"><span class="math inline">\(5 \frac{1}{4}\)</span></td>
<td style="text-align: center;">16</td>
<td style="text-align: center;"><span class="math inline">\(15 \frac{3}{4}\)</span></td>
<td style="text-align: center;"><strong>21</strong></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Totals</strong></td>
<td style="text-align: center;"><strong>6</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>18</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>24</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-7" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<p>The real data have sufficient sample size to do a <span class="math inline">\(\chi^2\)</span> test</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">non-English speaker</th>
<th style="text-align: center;">English speaker</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: center;">127</td>
<td style="text-align: center;">934</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: center;">1022</td>
<td style="text-align: center;">9336</td>
</tr>
</tbody>
</table>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-8" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<p><strong>Let’s run our null hypothesis test for real</strong></p>
<p><span class="math inline">\(H_0\)</span>: there is no difference in the proportions across explanatory groups</p>
<p><span class="math inline">\(H_A\)</span>: there <em>is</em> a difference in the proportions across explanatory groups</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a>dat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">127</span>, <span class="dv">1022</span>, <span class="dv">934</span>, <span class="dv">9336</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb17-2"><a href=""></a>dat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]  127  934
[2,] 1022 9336</code></pre>
</div>
</div>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-9" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a><span class="fu">chisq.test</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  dat
X-squared = 4.4741, df = 1, p-value = 0.03441</code></pre>
</div>
</div>
<p>We reject the null</p>
</section></section>
<section>
<section id="break-1" class="title-slide slide level1 center">
<h1>Break!</h1>

</section>
<section id="learning-objectives-2" class="slide level2">
<h2>Learning Objectives</h2>
<ol type="1">
<li>Understand <span class="alert">odds ratios</span>, their connection to <span class="alert">contingency analysis</span>, and their confidence intervals</li>
<li>Gain appreciation for missuses of <span class="math inline">\(P\)</span>-values and the partial solution offered by confidence intervals</li>
<li>Gain appreciation for the role of racism, eugenics, and personal bias (not statistical bias) in foundational statistics</li>
</ol>
</section>
<section id="review-chi2-statistic" class="slide level2">
<h2>Review: <span class="alert"><span class="math inline">\(\chi^2\)</span> statistic</span></h2>
<blockquote>
<p>The <span class="alert"><span class="math inline">\(\chi^2\)</span></span> statistic measures the discrepency between observed frequencies from the data and expected frequencies from the null hypothesis</p>
</blockquote>
<p><span class="alert"><span class="math inline">\(\chi^2\)</span> statistic</span> is calculated by summing up all <span class="math inline">\(n\)</span> <span class="math inline">\(\chi^2_i\)</span> values</p>
<p><span class="math display">\[\chi^2 = \sum_{i=1}^n \chi^2_i= \sum_{i=1}^n \frac{(O_i - E_i) ^ 2}{E_i}\]</span></p>
</section>
<section id="review-chi2-distribution" class="slide level2">
<h2>Review: <span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></h2>
<blockquote>
<p>The <strong><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></strong> is the sampling distribution for <span class="math inline">\(\chi^2\)</span> test statistic</p>
</blockquote>
<p><strong>Assumptions</strong></p>
<ul>
<li>None of the categories should have an expected frequency of less than 1</li>
<li>No more than 20% of the categories should have expected frequencies less than 5</li>
</ul>
</section>
<section id="chi2-distribution-4" class="slide level2">
<h2><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></h2>
<blockquote>
<p>The <strong><span class="alert"><span class="math inline">\(\chi^2\)</span> distribution</span></strong> is the sampling distribution for <span class="math inline">\(\chi^2\)</span> test statistic</p>
</blockquote>
<p>Under the null hypothesis, the more categories, the larger the test statistic</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>3 categories</strong></p>
<p><span class="math display">\[
\begin{aligned}
\chi^2 &amp;= \sum_{i=1}^3 \frac{(O_i - E_i) ^ 2}{E_i} \\
&amp;= \frac{(O_1 - E_1) ^ 2}{E_1} + \frac{(O_2 - E_2) ^ 2}{E_2} + \frac{(O_3 - E_3) ^ 2}{E_3}
\end{aligned}
\]</span></p>
</div><div class="column" style="width:50%;">
<p><strong>6 categories</strong></p>
<p><span class="math display">\[
\begin{aligned}
\chi^2 = &amp;\sum_{i=1}^3 \frac{(O_i - E_i) ^ 2}{E_i} \\
= &amp;\frac{(O_1 - E_1) ^ 2}{E_1} + \frac{(O_2 - E_2) ^ 2}{E_2} + \frac{(O_3 - E_3) ^ 2}{E_3} + \\
&amp;\frac{(O_4 - E_4) ^ 2}{E_4} + \frac{(O_5 - E_5) ^ 2}{E_5} + \frac{(O_6 - E_6) ^ 2}{E_6}
\end{aligned}
\]</span></p>
</div></div>
</section>
<section id="degrees-of-freedom-for-chi2-distribution-2" class="slide level2">
<h2><span class="alert">Degrees of freedom for <span class="math inline">\(\chi^2\)</span> distribution</span></h2>
<blockquote>
<p>The <span class="alert">degrees of freedom</span> of a <span class="math inline">\(\chi^2\)</span> statistic capture this fact that more categories equates to larger values</p>
</blockquote>
<p><strong>For goodness of fit test:</strong> <span class="math inline">\(df = \mathrm{(Number~of~categories)} - 1\)</span></p>
<p><strong>For contingency analysis:</strong> <span class="math inline">\(df = (\mathrm{Number~of~rows} - 1) \times (\mathrm{Number~of~columns} - 1)\)</span></p>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-10" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: left;">non-English speaker</th>
<th style="text-align: left;">English speaker</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: left;">127</td>
<td style="text-align: left;">934</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: left;">1022</td>
<td style="text-align: left;">9336</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Are non-English speakers more likely to undergo C-section in their first delivery?</p>
</blockquote>
<p>data from: Sentell et al.&nbsp;(2016). Maternal language and adverse birth outcomes in a statewide analysis. <em>Women &amp; Health</em></p>
</section>
<section id="null-hypothesis-significance-testing-7" class="slide level2">
<h2><span class="alert">Null Hypothesis Significance Testing</span></h2>
<ol type="1">
<li>State <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_\mathrm{A}\)</span></li>
<li>Calculate the test statistic</li>
<li>Generate the null distribution</li>
<li>Calculate the <span class="math inline">\(P\)</span>-value</li>
<li>Decide:
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if test statistic is <span class="math inline">\(\ge\)</span> critical value (<span class="math inline">\(P \le \alpha\)</span>)</li>
<li>Fail to reject <span class="math inline">\(H_0\)</span> if test statistic is &lt; critical value (<span class="math inline">\(P &gt; \alpha\)</span>)</li>
</ul></li>
</ol>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-11" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<p><strong>Let’s run our null hypothesis test for real</strong></p>
<p><span class="math inline">\(H_0\)</span>: there is no difference in the proportions across explanatory groups</p>
<p><span class="math inline">\(H_A\)</span>: there <em>is</em> a difference in the proportions across explanatory groups</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a>dat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">127</span>, <span class="dv">1022</span>, <span class="dv">934</span>, <span class="dv">9336</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb21-2"><a href=""></a>dat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]  127  934
[2,] 1022 9336</code></pre>
</div>
</div>
</section>
<section id="example-birth-outcomes-for-non-english-and-english-speakers-in-hawaiʻi-12" class="slide level2">
<h2>Example: birth outcomes for non-English and English speakers in Hawaiʻi</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href=""></a><span class="fu">chisq.test</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  dat
X-squared = 4.4741, df = 1, p-value = 0.03441</code></pre>
</div>
</div>
<p>We reject the null</p>
</section>
<section id="contingency-analysis" class="slide level2">
<h2>Contingency analysis</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th><strong>Contingency test</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of variables</td>
<td><strong>2</strong></td>
</tr>
<tr class="even">
<td>Type of data</td>
<td>categorical</td>
</tr>
<tr class="odd">
<td>Parameter</td>
<td><em>???</em></td>
</tr>
<tr class="even">
<td>Estimate</td>
<td><em>???</em></td>
</tr>
<tr class="odd">
<td>Sampling distribution</td>
<td><span class="math inline">\(\chi^2\)</span> distribution</td>
</tr>
<tr class="even">
<td>Test statistic</td>
<td><span class="math inline">\(\chi^2\)</span> statistic</td>
</tr>
</tbody>
</table>
</section>
<section id="contingency-analysis-1" class="slide level2">
<h2>Contingency analysis</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th><strong>Contingency test</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number of variables</td>
<td><strong>2</strong></td>
</tr>
<tr class="even">
<td>Type of data</td>
<td>categorical</td>
</tr>
<tr class="odd">
<td>Parameter</td>
<td><em>Odds ratio (OR)</em></td>
</tr>
<tr class="even">
<td>Estimate</td>
<td><span class="math inline">\(\hat{OR}\)</span></td>
</tr>
<tr class="odd">
<td>Sampling distribution</td>
<td><span class="math inline">\(\chi^2\)</span> distribution</td>
</tr>
<tr class="even">
<td>Test statistic</td>
<td><span class="math inline">\(\chi^2\)</span> statistic</td>
</tr>
</tbody>
</table>
<p>The <span class="alert">odds ratio</span> is the fraction of how likely a certain outcome is in one group compared to the other</p>
</section>
<section id="odds-and-odds-ratio" class="slide level2">
<h2>Odds and odds ratio</h2>
<p><span class="alert">Odds</span> describes how likely, e.g., C-section is compared to vaginal birth</p>
<p><span class="math display">\[
\text{Odds(C-section)} = \frac{Pr(\text{C-section})}{Pr(\text{vaginal birth})}
\]</span></p>
<p>If the <span class="alert">odds</span> are equal to 1, both outcomes are equally probable</p>
</section>
<section id="odds-and-odds-ratio-1" class="slide level2">
<h2>Odds and odds ratio</h2>
<p><span class="alert">Odds ratio</span> compares the odds of an outcome, e.g., C-section, across different groups</p>
<p>(note: only works for <code>2 x 2</code> contingency tables)</p>
<p><span class="math display">\[
\text{OR} = \frac{\text{Odds(C-section for non-English speakers)}}{\text{Odds(C-section for English speakers)}}
\]</span></p>
<p>If the <span class="alert">odds ratio</span> is equal to 1, both groups have the same odds</p>
<p><strong>Our null hypothesis is that the odds ratio is equal to 1</strong></p>
</section>
<section id="odds-and-odds-ratio-2" class="slide level2">
<h2>Odds and odds ratio</h2>
<p>The <span class="alert">odds ratio</span> we calculate from data is an estimate <span class="math inline">\(\hat{OR}\)</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: left;">non-English speaker</th>
<th style="text-align: left;">English speaker</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: left;">127</td>
<td style="text-align: left;">934</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: left;">1022</td>
<td style="text-align: left;">9336</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Odds <span class="math inline">\(\hat{O}\)</span></td>
<td style="text-align: left;">127/1022</td>
<td style="text-align: left;">934/9336</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{aligned}
\hat{OR} &amp;= \frac{\hat{O}_{nE}}{\hat{O}_{E}} \\
&amp;= \frac{127/1022}{934/9336} \\
&amp;= 1.242
\end{aligned}
\]</span></p>
</section>
<section id="odds-and-odds-ratio-3" class="slide level2">
<h2>Odds and odds ratio</h2>
<p>The <span class="alert">odds ratio</span> we calculate from data is an estimate <span class="math inline">\(\hat{OR}\)</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: left;">non-English speaker</th>
<th style="text-align: left;">English speaker</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: left;">127</td>
<td style="text-align: left;">934</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: left;">1022</td>
<td style="text-align: left;">9336</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Odds <span class="math inline">\(\hat{O}\)</span></td>
<td style="text-align: left;">127/1022</td>
<td style="text-align: left;">934/9336</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\hat{OR} = 1.242
\]</span></p>
<p><strong>Our null hypothesis is that the odds ratio is equal to 1</strong></p>
<p>Null hypothesis test: <em>Is 1.242 significantly different from 1?</em></p>
<ul>
<li><span class="math inline">\(P\)</span>-value</li>
<li>or…</li>
</ul>
</section>
<section id="confidence-interval-for-the-odds-ratio" class="slide level2">
<h2>Confidence interval for the odds ratio</h2>
<p><strong>95% CI</strong></p>
<ul>
<li>the range of values that contain 95% of the central probability of the sampling distribution for the estimate</li>
<li>the range will overlap the <em>true population parameter</em> 95% of the time in hypothetical repeat studies</li>
<li>if the 95% CI does not overlap the null hypothesis (e.g.&nbsp;<span class="math inline">\(OR = 1\)</span>) we reject the null at <span class="math inline">\(\alpha = 0.05\)</span></li>
<li>confidence intervals give us more information that <span class="math inline">\(P\)</span>-values alone</li>
</ul>
</section>
<section id="confidence-interval-for-the-odds-ratio-1" class="slide level2">
<h2>Confidence interval for the odds ratio</h2>
<p>The <strong>95% CI</strong> for the natural log of the odds ratio follows the nice (approximate) rule</p>
<p><span class="math display">\[
\text{95\% CI} = \ln(\hat{OR}) \pm 2 \times SE_\text{log-scale}
\]</span></p>
<p>An even better approximation is</p>
<p><span class="math display">\[
\text{95\% CI} = \ln(\hat{OR}) \pm 1.96 \times SE_\text{log-scale}
\]</span></p>
</section>
<section id="confidence-interval-for-the-odds-ratio-2" class="slide level2">
<h2>Confidence interval for the odds ratio</h2>
<p><span class="math display">\[
\text{95\% CI} = \ln(\hat{OR}) \pm 1.96 \times SE_\text{log-scale}
\]</span></p>
<p>But what is <span class="math inline">\(SE_\text{log-scale}\)</span>? Just take my word for it:</p>
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: left;">group 1</th>
<th style="text-align: left;">group 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">response 1</td>
<td style="text-align: left;">a</td>
<td style="text-align: left;">c</td>
</tr>
<tr class="even">
<td style="text-align: right;">response 2</td>
<td style="text-align: left;">b</td>
<td style="text-align: left;">d</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<p><span class="math display">\[
SE_\text{log-scale} = \sqrt{\frac{1}{a} + \frac{1}{b} + \frac{1}{c} + \frac{1}{d}}
\]</span></p>
</div></div>
</section>
<section id="confidence-interval-for-the-odds-ratio-3" class="slide level2">
<h2>Confidence interval for the odds ratio</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: left;">non-English speaker</th>
<th style="text-align: left;">English speaker</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: left;">127</td>
<td style="text-align: left;">934</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: left;">1022</td>
<td style="text-align: left;">9336</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{aligned}
\text{95\% CI} &amp;= \ln(\hat{OR}) \pm 1.96 \times SE_\text{log-scale} \\
&amp;= \ln(1.242) \pm 1.96 \times \sqrt{\frac{1}{127} + \frac{1}{1022} + \frac{1}{934} + \frac{1}{9336}} \\
&amp;= \ln(1.242) \pm 1.96 \times 0.100 \\
&amp;= \ln(1.242) \pm 0.196
\end{aligned}
\]</span></p>
</section>
<section id="confidence-interval-for-the-odds-ratio-4" class="slide level2">
<h2>Confidence interval for the odds ratio</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: left;">non-English speaker</th>
<th style="text-align: left;">English speaker</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Primary Caesarean delivery</td>
<td style="text-align: left;">127</td>
<td style="text-align: left;">934</td>
</tr>
<tr class="even">
<td style="text-align: right;">Primary vaginal delivery</td>
<td style="text-align: left;">1022</td>
<td style="text-align: left;">9336</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{aligned}
\text{95\% CI} &amp;= \ln(\hat{OR}) \pm 1.96 \times SE_\text{log-scale} \\
&amp;= \ln(1.242) \pm 0.196
\end{aligned}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a>ci95logLo <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="fl">1.242</span>) <span class="sc">-</span> <span class="fl">0.196</span></span>
<span id="cb25-2"><a href=""></a>ci95logHi <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="fl">1.242</span>) <span class="sc">+</span> <span class="fl">0.196</span></span>
<span id="cb25-3"><a href=""></a></span>
<span id="cb25-4"><a href=""></a><span class="co"># convert back to linear (not log) measurements</span></span>
<span id="cb25-5"><a href=""></a><span class="fu">exp</span>(<span class="fu">c</span>(ci95logLo, ci95logHi))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.020939 1.510926</code></pre>
</div>
</div>
</section>
<section id="chi2-contingency-tests-are-all-approximate" class="slide level2">
<h2><span class="math inline">\(\chi^2\)</span> contingency tests are all approximate</h2>
<p>Here is a more accurate what of getting all the same information:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href=""></a><span class="co"># make the contingency table in R</span></span>
<span id="cb27-2"><a href=""></a>d <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">127</span>, <span class="dv">1022</span>, <span class="dv">934</span>, <span class="dv">9336</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a><span class="co"># an "exact" test without the chi-sqrd assumptions</span></span>
<span id="cb28-2"><a href=""></a><span class="fu">fisher.test</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="chi2-contingency-tests-are-all-approximate-1" class="slide level2">
<h2><span class="math inline">\(\chi^2\)</span> contingency tests are all approximate</h2>
<p>Here is a more accurate what of getting all the same information:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a><span class="fu">fisher.test</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  d
p-value = 0.0321
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 1.012444 1.514392
sample estimates:
odds ratio 
  1.242103 </code></pre>
</div>
</div>
</section>
<section id="why-do-we-care-so-much-about-confidence-intervals" class="slide level2">
<h2>Why do we care so much about <span class="alert">confidence intervals</span>?</h2>
<p><strong>There’s a replication crisis in biostatistics</strong></p>
<ul>
<li>Studies will publish a “significant” finding (one with <span class="math inline">\(P\)</span>-value <span class="math inline">\(\le 0.05\)</span>)</li>
<li>Other researchers will try to reproduce that finding, and more often than not, <strong>they fail</strong></li>
<li>Are any of our insights valid?!</li>
</ul>
<p><a href="https://www.tandfonline.com/doi/full/10.1080/00031305.2018.1527253">Blakeley et al.&nbsp;(2019)</a> write about this problem in an article titled:</p>
<div style="text-align: center;">
<p><em>Abandon Statistical Significance</em></p>
</div>
<p>(i.e.&nbsp;no more <span class="math inline">\(P\)</span>-values, please)</p>
</section>
<section id="why-do-we-care-so-much-about-confidence-intervals-1" class="slide level2">
<h2>Why do we care so much about <span class="alert">confidence intervals</span>?</h2>
<p><strong>There’s a replication crisis in biostatistics</strong></p>
<p>Confidence intervals are a small, simple, incomplete fix: they let us keep doing statistics pretty much the same, but CIs are <em>more informative</em> and thus less prone to <em>P-hacking</em></p>
</section>
<section id="why-do-we-care-so-much-about-confidence-intervals-2" class="slide level2">
<h2>Why do we care so much about <span class="alert">confidence intervals</span>?</h2>
<p><strong>There’s a replication crisis in biostatistics</strong></p>
<p>Confidence intervals are a small, simple, incomplete fix</p>
<p>An example with odds ratios (the null hypothesis is <span class="math inline">\(OR = 1\)</span>)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\(P\)</span>-value</th>
<th><span class="math inline">\(\chi^2\)</span> stat</th>
<th>odds ratio</th>
<th>(95% CI)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(P = 0.01\)</span></td>
<td>6.63</td>
<td>1.211</td>
<td>(1.011, 1.425)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(P = 0.01\)</span></td>
<td>6.63</td>
<td>1.003</td>
<td>(1.001, 1.004)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(P = 0.01\)</span></td>
<td>6.63</td>
<td>2.327</td>
<td>(1.983, 3.782)</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(P\)</span>-values are all the same, but due to different sample sizes and true effect sizes, odds ratios and confidence intervals are wildly different, with some warranting our interest and others not</p>
</section>
<section id="why-do-we-care-so-much-about-confidence-intervals-3" class="slide level2">
<h2>Why do we care so much about <span class="alert">confidence intervals</span>?</h2>
<p><strong>There’s a replication crisis in biostatistics</strong></p>
<p>Confidence intervals are a small, simple, incomplete fix</p>
<p>An example with odds ratios (the null hypothesis is <span class="math inline">\(OR = 1\)</span>)</p>
<table class="caption-top">
<colgroup>
<col style="width: 18%">
<col style="width: 25%">
<col style="width: 20%">
<col style="width: 16%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(P\)</span>-value</th>
<th><span class="math inline">\(\chi^2\)</span> stat</th>
<th>odds ratio</th>
<th>(95% CI)</th>
<th>conclusion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(P = 0.01\)</span></td>
<td>6.63</td>
<td>1.211</td>
<td>(1.011, 1.425)</td>
<td>Could be interesting, needs more samples</td>
</tr>
<tr class="even">
<td><span class="math inline">\(P = 0.01\)</span></td>
<td>6.63</td>
<td>1.003</td>
<td>(1.001, 1.004)</td>
<td>Huge sample size, biologically meaningless</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(P = 0.01\)</span></td>
<td>6.63</td>
<td>2.327</td>
<td>(1.983, 3.782)</td>
<td>Clearly there’s an effect</td>
</tr>
</tbody>
</table>
</section>
<section id="how-did-we-get-here" class="slide level2">
<h2>How did we get here?</h2>
<p><strong>There’s a replication crisis in biostatistics</strong></p>
</section>
<section id="how-did-we-get-here-1" class="slide level2">
<h2>How did we get here?</h2>
<p><strong>There’s a replication crisis in biostatistics</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="../img/bernoulli_falacy.jpg"></p>
</div><div class="column" style="width:50%;">
<p>Aubrey Clayton argues that “political agendas” of early statisticians drove them to develop methods that could prove their own “unpopular” beliefs and shield their “controversial” views behind the guise of “objectivity”</p>
<p>(quotes are not Clayton’s…I’m building suspense…)</p>
</div></div>
</section>
<section id="how-did-we-get-here-2" class="slide level2">
<h2>How did we get here?</h2>
<p><strong>There’s a replication crisis in biostatistics</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Early statisticians</strong></p>
<p>Ronald Fisher</p>
<ul>
<li>promoted <span class="math inline">\(P\)</span>-values</li>
<li>developed that “Fisher exact test” thing</li>
<li>lots more we’ll be talking about</li>
</ul>
<p>Karl Pearson</p>
<ul>
<li>developed the <span class="math inline">\(chi^2\)</span> test</li>
<li>developed methods for correlation</li>
<li>lots more we’ll be talking about</li>
</ul>
</div><div class="column" style="width:50%;">
<p>“political agendas” = eugenics</p>
<p>“unpopular” beliefs = white supremacy</p>
<p>“controversial” views = genocide is necessary</p>
</div></div>
</section>
<section id="disease-at-the-root-disease-in-the-shoot" class="slide level2">
<h2>Disease at the root, disease in the shoot</h2>
<div class="columns">
<div class="column" style="width:70%;">
<p><em>“Available scientific knowledge provides a firm basis for believing that the groups of mankind differ in their innate capacity for intellectual and emotional development”</em></p>
<p><em>“I am sorry that there should be propaganda in favour of miscegenation</em> [bigoted term for marriage between perceived racial groups] <em>in North America as I am sure it can do nothing but harm”</em></p>
<p><em>“Unfortunately, considerable propaganda is now being developed to convince the public that cigarette smoking is dangerous”</em> [Fisher was funded by the tobacco industry]</p>
</div><div class="column" style="width:30%;">
<p><img data-src="../img/fisher.jpeg"></p>
<p>Ronald Fisher</p>
<ul>
<li>Racist</li>
<li>Eugenicist</li>
<li>Pawn of big tobacco</li>
</ul>
</div></div>
</section>
<section id="disease-at-the-root-disease-in-the-shoot-1" class="slide level2">
<h2>Disease at the root, disease in the shoot</h2>
<div class="columns">
<div class="column" style="width:30%;">
<p><img data-src="../img/Karl_Pearson_1912.jpg"></p>
<p>Karl Pearson</p>
<ul>
<li>Racist</li>
<li>Eugenicist</li>
<li>Antisemite</li>
</ul>
</div><div class="column" style="width:70%;">
<p><em>“My view—and I think it may be called the scientific view of a nation—is that of an organized whole, kept up to a high pitch of internal efficiency by insuring that its numbers are substantially recruited from the better stocks, and kept up to a high pitch of external efficiency by contest, chiefly by way of war with inferior races”</em></p>
<p><em>“It is a false view of human solidarity, a weak humanitarianism, not a true humanism, which regrets that a capable and stalwart race of white men should replace a dark-skinned tribe…”</em></p>
</div></div>
</section>
<section id="disease-at-the-root-disease-in-the-shoot-2" class="slide level2">
<h2>Disease at the root, disease in the shoot</h2>
<div class="columns">
<div class="column" style="width:30%;">
<p><img data-src="../img/Karl_Pearson_1912.jpg"></p>
<p>Karl Pearson</p>
<ul>
<li>Racist</li>
<li>Eugenicist</li>
<li>Antisemite</li>
</ul>
</div><div class="column" style="width:70%;">
<p><em>“It is a false view of human solidarity, a weak humanitarianism, not a true humanism, which regrets that a capable and stalwart race of white men should replace a dark-skinned tribe which can neither utilize its land for the full benefit of mankind, nor contribute its quota to the common stock of human knowledge.”</em></p>
<p><em>“Taken on the average, and regarding both sexes, this alien Jewish population is somewhat inferior physically and mentally to the native population”</em></p>
</div></div>
</section>
<section id="disease-at-the-root-disease-in-the-shoot-3" class="slide level2">
<h2>Disease at the root, disease in the shoot</h2>
<div style="text-align: center;">
<p>What do we do? Why learn “statistics”?</p>
</div>
</section>
<section id="disease-at-the-root-disease-in-the-shoot-4" class="slide level2">
<h2>Disease at the root, disease in the shoot</h2>
<p>What do we do? Why learn “statistics”?</p>
<ul>
<li>Why learn statistics?
<ul>
<li>It holds a powerful position in science and society</li>
<li>To undo harm, “beat them at their own game”</li>
<li>Some methods (even <span class="math inline">\(P\)</span>-values) not wrong, just poorly applied</li>
<li>Those f@&amp;%kers were <strong>NOT</strong> geniuses, others would have developed similar ideas and did (e.g.&nbsp;Anil Kumar Gain)</li>
</ul></li>
</ul>
</section>
<section id="disease-at-the-root-disease-in-the-shoot-5" class="slide level2">
<h2>Disease at the root, disease in the shoot</h2>
<p>What do we do? Why learn “statistics”?</p>
<ul>
<li>Stop the spread
<ul>
<li>Confront the history</li>
<li>Remove its influence on the contemporary</li>
</ul></li>
<li>Be intentional and self-reflective about how and why we use statistics</li>
</ul>
</section>
<section id="disease-at-the-root-disease-in-the-shoot-6" class="slide level2">
<h2>Disease at the root, disease in the shoot</h2>
<p>What do we do? Why learn “statistics”?</p>
<ul>
<li>Seek and embrace alternative knowledge systems
<ul>
<li>Reject the idea that western science is a superior knowledge system</li>
<li>Do not be extractive in connection to other knowledge systems</li>
<li>Check out Ethnomathematics here at UH</li>
<li>Let’s see if we can decolonize statistics</li>
</ul></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="07-chi-sq-slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="07-chi-sq-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="07-chi-sq-slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="07-chi-sq-slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="07-chi-sq-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="07-chi-sq-slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="07-chi-sq-slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="07-chi-sq-slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="07-chi-sq-slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="07-chi-sq-slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>