{
  "hash": "07163f99fe2f76a02e35e01d35b05afb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The t-test\"\n---\n\n\n\n## La hua ʻōlelo o ka pule\n\n::: {style=\"text-align: center;\"}\n[lapu]{.alert}\n:::\n\n## Learning Objectives\n\n1. Analyze a single numerical variable using the [one-sample $t$-test]{.alert}\n2. Quantify uncertainty in the sample mean using confidence intervals\n3. Compare the means of *two* numerical variables using the [two-sample $t$-test]{.alert}\n4. Quantify uncertainty in the difference between means using confidence intervals\n\n## Which way do Cook pines lean?\n\nCook pine (*Araucaria columnaris*) is endemic to New Caledonia (Southern hemisphere), but common in many parts of the world, including Hawaiʻi\n\n![From Johns *et al.* (2017): \"Typical cultivated stand of *Araucaria columnaris* at the University of California, Irvine campus\"](/img/johns-etal-2017-fig1.jpeg){width=\"40%\"}\n\n## Which way do Cook pines lean?\n\nJohns *et al.* (2017) measured axial lean of Cook pines planted all over the world. Their biological hypothesis was that Cook pines lean toward the equator.\n\nAxial lean:\n\n* Positive value $\\rightarrow$ tree leans toward equator\n\n* Negative value $\\rightarrow$ tree leans away from equator\n\n## Which way do Cook pines lean?\n\nJohns *et al.* (2017) measured axial lean of Cook pines planted all over the world. Their biological hypothesis was that Cook pines lean toward the equator.\n\nAxial lean:\n\n* Positive value $\\rightarrow$ tree leans toward equator\n\n* Negative value $\\rightarrow$ tree leans away from equator\n\nConsider small random sample ($n = 5$)\n\n> -0.04, 0.00, 0.06, 0.12, 0.20\n\n\n::: {.cell}\n\n:::\n\n\n## Which way do Cook pines lean?\n\n> `-0.04, 0.00, 0.06, 0.12, 0.20`\n\n| $\\overline{Y}$     | $s$             | $s^2$            |\n|:------------------:|:---------------:|:----------------:|\n| 0.068 | 0.095 | 0.009 |\n\n::: {.pause-think}\n- What is a reasonable null hypothesis?\n:::\n\n## Which way do Cook pines lean?\n\n> `-0.04, 0.00, 0.06, 0.12, 0.20`\n\n| $\\overline{Y}$     | $s$             | $s^2$            |\n|:------------------:|:---------------:|:----------------:|\n| 0.068 | 0.095 | 0.009 |\n\n::: {.pause-think}\n$H_0$: The mean axial lean is 0 ($\\mu = 0$)\n\n$H_A$: The mean axial lean is not 0 ($\\mu \\ne 0$)\n:::\n\n## The sampling distribution of the difference between sample and population mean\n\nWe want to know the sampling distribution for the difference between sample mean $\\overline{Y}$ and the population mean $\\mu$\n\n$Z$-standardization gives us a standard normal sampling distribution (mean = 0, sd = 1):\n\n$$Z = \\frac{\\overline{Y} - \\mu}{\\sigma_{\\overline{Y}}}$$\n\nBUT, we don't know the population standard error of the mean $\\sigma_{\\overline{Y}}$, we have to estimate from the sample $\\textrm{SE}_{\\overline{Y}}$.\n\n## Student's $t$ distribution\n\n> The difference between the sample mean and the true mean ($\\overline{Y} - \\mu$), divided by the estimated standard error ($\\textrm{SE}_{\\overline{Y}}$), has a Student's $t$-distribution with $n - 1$ degrees of freedom.\n\n## Student's $t$ distribution\n\nThe $t$ distribution accounts for the fact that we have to estimate both $\\mu$ and $\\sigma$ from the sample\n\n$$t = \\frac{\\overline{Y} - \\mu}{\\textrm{SE}_{\\overline{Y}}}$$\n\n$t$ is like $Z$ except there is uncertainty about the sample standard error\n\n## Student's $t$ distribution\n\nThe $t$ distribution accounts for the fact that we have to estimate both $\\mu$ and $\\sigma$ from the sample\n\n$$t = \\frac{\\overline{Y} - \\mu}{\\textrm{SE}_{\\overline{Y}}}$$\n\n$t$ is like $Z$ except there is uncertainty about the sample standard error\n\n::: {.pause-think}\nHow would you expect the uncertainty of the estimated standard error to affect the shape of the $t$ distribution relative to the $Z$ distribution?\n:::\n\n## Student's $t$ distribution\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-t-test-slides_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=7.5in}\n:::\n:::\n\n\n## Student's $t$ distribution\n\nThe $t$ distribution is like the standard normal ($Z$) but has longer tails that account for the fact that we estimate $\\sigma$ from the sample\n\nThis matters because $P$-values are calculated by integrating the tails of the distribution. Change in the shape of the tails affect your inference!\n\n## [One-sample $t$-test]{.alert}\n\n> The [one-sample $t$-test]{.alert} compares the mean of a random sample for a normal population with the population mean proposed in a null hypothesis\n\n## Null hypothesis testing\n\n1. State null and alternative hypotheses\n2. Calculate test statistic\n2. Identify null distribution\n3. Calculate $P$-value\n4. Decide:\n\n    - Reject null\n    - Fail to reject null\n\n## 1. Null and alternative hypotheses\n\n$H_0$: The true (population) mean equals $\\mu_0$\n\n$H_A$: The true (population) mean does not equal $\\mu_0$\n\nOften, $\\mu_0 = 0$, like in our example:\n\n$H_0$: The mean axial lean is 0 ($\\mu = 0$)\n\nBut $\\mu_0$ could be something else depending on what you're testing\n\n## 2. The $t$ test statistic\n\n$$t = \\frac{\\overline{Y} - \\mu_0}{\\text{SE}_{\\overline{Y}}}$$\n\n## Which way do Cook pines lean?\n\n> `-0.04, 0.00, 0.06, 0.12, 0.20`\n\n| $\\overline{Y}$     | $s$             | $s^2$            |\n|:------------------:|:---------------:|:----------------:|\n| 0.068 | 0.095 | 0.009 |\n\n::: {.pause-think}\nCalculate $\\text{SE}_{\\overline{Y}}$ and the $t$ test statistic.\n:::\n\n## Which way do Cook pines lean?\n\n> `-0.04, 0.00, 0.06, 0.12, 0.20`\n\n| $\\overline{Y}$     | $s$             | $s^2$            |\n|:------------------:|:---------------:|:----------------:|\n| 0.068 | 0.095 | 0.009 |\n\n::: {.pause-think}\n$$\\text{SE}_{\\overline{Y}} = \\frac{s}{\\sqrt{n}} = \\frac{0.095}{\\sqrt{5}} = 0.043$$\n\n$$t = \\frac{\\overline{Y} - \\mu_0}{\\text{SE}_{\\overline{Y}}} = \\frac{0.068 - 0}{0.043} = 1.592$$\n:::\n\n## 3. The $t$ distribution is the sampling distribution for $t$\n\nRemember: the $t$-distribution comes from the standard normal, but with added uncertainty about the standard deviation.\n\nWe *estimate* the standard deviation, and account for its uncertainty, with a [$\\chi^2$ distribution]{.alert}.\n\nThus our $t$-distribution has degrees of freedom: $df = n - 1$\n\nFor our study, $5 - 1 = 4$ degrees of freedom\n\n## 3. The $t$ distribution is the sampling distribution for $t$\n\nThe $t_4$ distribution looks like this:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-t-test-slides_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=5in}\n:::\n:::\n\n\n## 4. $P$-values\n\n[One-sample $t$-test]{.alert} is usually two-sided because we would be equally surprised by a positive or negative difference from $\\mu_0$\n\nThe $t$ distribution is symmetrical around 0, so we can find the area under of the curve greater/less than and our test statistic and use that same value, times -1, on the other side\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-t-test-slides_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=5in}\n:::\n:::\n\n\n## 4. $P$-values\n\nFor a two-tailed test (most common)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nP_value <- 2 * pt(\n  q = 1.592,\n  df = 4,\n  lower.tail = FALSE\n)\n\nP_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1865996\n```\n\n\n:::\n:::\n\n\n## 4. $P$-values\n\nFor a one-tailed test (less common)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nP_value <- pt(\n  q = 1.592,\n  df = 4,\n  lower.tail = FALSE # test if mu > mu_0\n  # lower.tail = TRUE # test if mu < mu_0\n)\n```\n:::\n\n\n## 4. $P$-values: Even easier with the function `t.test`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(-0.04, 0.00, 0.06, 0.12, 0.20)\nt.test(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  y\nt = 1.5922, df = 4, p-value = 0.1866\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -0.05057729  0.18657729\nsample estimates:\nmean of x \n    0.068 \n```\n\n\n:::\n:::\n\n\n## 5. Decide\n\nSince $P = 0.187$ is greater than $\\alpha = 0.05$, we fail to reject the null hypothesis.\n\nWe don't have enough evidence to conclude that Cook pines lean towards the equator from this sample\n\n## Confidence intervals for the mean\n\nRecall that previously we used the $2~\\mathrm{SE}$ approximation\n\nThe $t$ intervals are more precise assuming the population is truly normally distributed\n\n## 95% confidence intervals for the mean\n\nRecall definition of confidence intervals: 95% of the time, 95% confidence intervals will include the true population mean\n\n## 95% confidence intervals for the mean\n\n$$-t_{0.05(2),\\mathit{df}} < \\frac{\\overline{Y} - \\mu}{\\text{SE}_{\\overline{Y}}} < t_{0.05(2),\\mathit{df}}$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-t-test-slides_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=7.5in}\n:::\n:::\n\n\n## 95% confidence intervals for the mean\n\n$$\\overline{Y}-t_{0.05(2),\\mathit{df}} \\text{SE}_{\\overline{Y}}< \\mu < \\overline{Y}+t_{0.05(2),\\mathit{df}} \\text{SE}_{\\overline{Y}}$$\n\nFor $n = 5$, we have 4 degrees of freedom, so we calculate $t_{0.05(2),4}$\n\n::: {.pause-think}\nWhich function do we need for calculating the confidence interval? `dt`, `pt`, `qt`, or `rt`?\n:::\n\n## 95% confidence intervals for the mean\n\n$$\\overline{Y}-t_{0.05(2),\\mathit{df}} \\text{SE}_{\\overline{Y}}< \\mu < \\overline{Y}+t_{0.05(2),\\mathit{df}} \\text{SE}_{\\overline{Y}}$$\n\nFor $n = 5$, we have 4 degrees of freedom, so we calculate $t_{0.05(2),4}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncritical_value <- qt(0.025, 4, lower.tail = FALSE)\ncritical_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.776445\n```\n\n\n:::\n:::\n\n\n$$t_{0.05(2),4} = 2.776$$\n\n## 95% confidence intervals for the mean\n\n$$\\overline{Y}-t_{0.05(2),\\mathit{df}} \\text{SE}_{\\overline{Y}}< \\mu < \\overline{Y}+t_{0.05(2),\\mathit{df}} \\text{SE}_{\\overline{Y}}$$\n\n$$\\text{SE}_{\\overline{Y}} = 0.043$$\n$$t_{0.05(2),4} = 2.776$$\n\nLower 95% CI: $0.068 - 2.776 \\times 0.043 = -0.051$\n\nUpper 95% CI: $0.068 + 2.776 \\times 0.043 = 0.187$\n\n## Confidence intervals for the mean\n\nCheck it out, given to us by `t.test`:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  y\nt = 1.5922, df = 4, p-value = 0.1866\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -0.05057729  0.18657729\nsample estimates:\nmean of x \n    0.068 \n```\n\n\n:::\n:::\n\n\n## Great! What if I want to compare **two** variables?\n\n## Great! What if I want to compare **two** variables?\n\nTwo-sample t-test to the rescue\n\n## There are two ways to compare two means\n\n* [Paired $t$-test]{.alert} provides a control for extraneous\nvariation and therefore have more power and precision.\n\n* [Two-sample $t$-tests]{.alert} are often easier because you do not have to resample the same unit as in a paired comparison.\n\n> In the *paired* design, both treatments are applied to every sampled unit. In the *two-sample* design, each treatment group is composed of an independent, random sample of units\n\n## [Paired $t$-test]{.alert}\n\nWe used a [paired $t$-test]{.alert} to compare stomatal traits on the upper and lower surface of the same leaves. The sampled units are the species, the treatments are the leaf surface\n\nBecause each member of a pair shares much in common, researchers can ignore extra variation (e.g. difference in stomatal traits among species) and just focus on effect of treatment\n\nExamples of paired comparisons:\n\n* Before and after treatment\n* Clones one with a treatment and one without\n\n## [Paired $t$-test]{.alert}\n\n> Paired measurements are converted to a single measurement by taking the difference between them\n\nIn other words, a [paired $t$-test]{.alert} is a one-sample $t$-test\n\n* The null hypothesis of difference in means is denoted $\\mu_{d0}$\n* Degrees of freedom is number of pairs $- 1$\n\n## Assumptions of [Paired $t$-test]{.alert}\n\n* Pairs are randomly sampled from a population\n* The differences are normally distributed\n\nDoes NOT assume that individual values are normally distributed\n\n## Confidence intervals for the difference in means\n\nIdentical to confidence intervals for mean of a single sample\n\nWe just replace $\\overline{Y}$ with $\\overline{d}$, $\\text{SE}_{\\overline{Y}}$ with $\\text{SE}_{\\overline{d}}$, and $\\mu$ with $\\mu_d$\n\n## 95% confidence intervals for difference in means\n\n$$\\overline{d}-t_{0.05(2),\\mathit{df}} \\text{SE}_{\\overline{d}}< \\mu_d < \\overline{d}+t_{0.05(2),\\mathit{df}} \\text{SE}_{\\overline{d}}$$\n\n## There are two ways to compare two means\n\n* [Paired $t$-test]{.alert} provides a control for extraneous\nvariation and therefore have more power and precision.\n\n* [Two-sample $t$-tests]{.alert} are often easier because you do not have to resample the same unit as in a paired comparison.\n\n> In the *paired* design, both treatments are applied to every sampled unit. In the *two-sample* design, each treatment group is composed of an independent, random sample of units\n\n## [Two-sample $t$-test]{.alert}\n\n\"Compare the means of two  of a numerical variable between two independent groups\" when there is no natural pairing of samples\n\nThe sample sizes do not have to be the same in each group.\n\n## Assumptions of [Two-sample $t$-test]{.alert}\n\n* \"Each of the two samples is a random sample from its population\"\n* \"The numerical variable is normally distributed in each population\"\n* \"The standard deviation (and variance) of the numerical variable is the same in both populations\" (we will eventually relax this assumption)\n\n## Cost of resistance to Aphids in lettuce\n\n* Some lettuce genotypes are *Susceptible* and others are\n*Resistant* to aphids.\n* Why isn't all lettuce resistant to aphids?\n* Let us test the hypothesis that resistant lettuce has\nlower fitness in the absence of aphids.\n* Fitness = number of seeds per plant\n\n| Genotype | $\\overline{Y}_i$ | $s_i$ | $n_i$ |\n|:--------:|:----------------:|:------|:-----:|\n| Susceptible | 720 | 223.6 | 15 |\n| Resistant | 582 | 277.3 | 16 |\n\n# Parameter estimation and confidence intervals\n\n## Standard error of the difference in means\n\n| Genotype | $\\overline{Y}_i$ | $s_i$ | $n_i$ |\n|:--------:|:----------------:|:------|:-----:|\n| Susceptible | 720 | 223.6 | 15 |\n| Resistant | 582 | 277.3 | 16 |\n\nThe pooled sample variance is $s_p^2 = \\frac{\\mathit{df}_1 s_1^2 + \\mathit{df}_2 s_2^2}{\\mathit{df}_1 +\\mathit{df}_2}$\n\n$s^2_1$ is the sample variance of sample 1\n\n$s^2_2$ is the sample variance of sample 2\n\n$\\mathit{df}_1 = n_1 - 1$; $\\mathit{df}_2 = n_2 - 1$;\n\ntotal degrees of freedom for $t$ distribution: $\\mathit{df} = \\mathit{df}_1 +\\mathit{df}_2$\n\n$$s_p^2 = \\frac{14 \\times 223.6 ^2 + 15 \\times 277.3^2}{14 + 15} = 63909.889310$$\n\n## Standard error of the difference in means\n\n| Genotype | $\\overline{Y}_i$ | $s_i$ | $n_i$ |\n|:--------:|:----------------:|:------|:-----:|\n| Susceptible | 720 | 223.6 | 15 |\n| Resistant | 582 | 277.3 | 16 |\n\nThe standard error of the difference in means is $\\mathrm{SE}_{\\overline{Y}_1 - \\overline{Y}_2} = \\sqrt{s_p^2 (\\frac{1}{n_1} + \\frac{1}{n_2})}$\n\n$$\\mathrm{SE}_{\\overline{Y}_1 - \\overline{Y}_2} = \\sqrt{63909.889310 (\\frac{1}{15} + \\frac{1}{16})} = 90.8571812$$\n\n## 95% confidence intervals for difference in means\n\n$$(\\overline{Y}_1 - \\overline{Y}_2)-t_{0.05(2),\\mathit{df}} \\text{SE}_{\\overline{Y}_1 - \\overline{Y}_2} < (\\mu_1 - \\mu_2) < (\\overline{Y}_1 - \\overline{Y}_2)+t_{0.05(2),\\mathit{df}} \\text{SE}_{\\overline{Y}_1 - \\overline{Y}_2}$$\n\n$\\mathit{df} = 29$\n\n$t_{0.05(2),\\mathit{29}} = 2.0452296$\n\nLower CI:\n\n$$(720 - 582) - 2.0452296 \\times 90.8571812 = -47.8238001$$\n\nUpper CI:\n\n$$(720 - 582) + 2.0452296 \\times 90.8571812 = 323.8238001$$\n\n## 95% confidence intervals for difference in means\n\nWe estimated the susceptible genotypes produce an average of 720 - 582 = 138 more seeds, but our 95% CI is -48 to 324.\n\n0 difference in fitness between genotypes is within the plausible range of values given our data.\n\n# Hypothesis testing\n\n## 1. Null and alternative hypotheses\n\n$H_0$: $\\mu_1 = \\mu_2$\n\n$H_A$: $\\mu_1 \\ne \\mu_2$\n\nIn our case, the mean fitness of resistant and susceptible lettuce genotypes is the same.\n\n## 2. The $t$ test statistic\n\n$$t = \\frac{\\overline{Y}_1 - \\overline{Y}_2}{\\text{SE}_{\\overline{Y}_1 - \\overline{Y}_2}}$$\n\n| Genotype | $\\overline{Y}_i$ | $s_i$ | $n_i$ |\n|:--------:|:----------------:|:------|:-----:|\n| Susceptible | 720 | 223.6 | 15 |\n| Resistant | 582 | 277.3 | 16 |\n\n$$t = \\frac{720 - 582}{90.8571812} = 1.5188673$$\n\n## 3. The $t$ distribution is the sampling distribution for $t$\n\nDegrees of freedom: $\\mathit{df}_1 = n_1 - 1$; $\\mathit{df}_2 = n_2 - 1$;\n\ntotal degrees of freedom for $t$ distribution: $\\mathit{df} = \\mathit{df}_1 +\\mathit{df}_2$\n\nFor our study, $(15 - 1) + (16 - 1) = 29$ degrees of freedom\n\nThe $t_{29}$ distribution looks like this:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-t-test-slides_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=5in}\n:::\n:::\n\n\n## 4. $P$-values\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09-t-test-slides_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=5in}\n:::\n:::\n\n\n## 4. $P$-values\n\nFor a two-tailed test (most common)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nP_value <- 2 * pt(\n  q = 1.518867,\n  df = 29,\n  lower.tail = FALSE\n)\n\nP_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.139624\n```\n\n\n:::\n:::\n\n\n## 5. Decide\n\nSince $P = 0.14$ is greater than $\\alpha = 0.05$, we fail to reject the null hypothesis.\n\nWe don't have enough evidence to conclude that susceptible genotypes of lettuc have greater fitness than resistant genotypes in the absence of aphids.\n\n## Difference between [Two-sample $t$-test]{.alert} and [Welch's $t$-test]{.alert}\n\n[Welch's $t$-test]{.alert} does NOT assume \"the standard deviation (and variance) of the numerical variable is the same in both populations\"\n\n## Difference between [Two-sample $t$-test]{.alert} and [Welch's $t$-test]{.alert}\n\n[Welch's $t$-test]{.alert} is the default in *R*\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(dat$n_seeds ~ dat$genotype)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  dat$n_seeds by dat$genotype\nt = -1.5296, df = 28.39, p-value = 0.1372\nalternative hypothesis: true difference in means between group Resistant and group Susceptible is not equal to 0\n95 percent confidence interval:\n -322.68656   46.68656\nsample estimates:\n  mean in group Resistant mean in group Susceptible \n                      582                       720 \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "09-t-test-slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}