{
  "hash": "8627453aff97f12932f81cc66e7354b2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Describing data\"\n---\n\n\n\n## Ka hua ʻōlelo o ka haʻawina\n\n::: {style=\"text-align: center;\"}\n[ʻokana]{.alert}\n:::\n\n## The Moku System: Managing Biocultural Resources for Abundance within Social-Ecological Regions in Hawaiʻi\n\n![](/img/winter_moku.png)\n\n# How do we describe [data]{.alert}?\n\n## How do we describe [data]{.alert}?\n\n- Why do we make the choices we make in describing data?\n- These choices get bundled into knowledge system\n- Whose knowledge system(s) do we learn and why?\n\n## Learning Objectives\n\n1. Describe the *location* of numerical variables using the [mean]{.alert} and [median]{.alert}\n2. Describe the *spread* of numerical variables using the [standard deviation]{.alert}, [variance]{.alert}, [coefficient of variation]{.alert}, and [interquartile range]{.alert}\n3. Describe categorical variables using the [proportion]{.alert}\n4. Know when to use different descriptive statistics\n\n## Describing location and spread of numerical data\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-describing-data-slides_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=384}\n:::\n:::\n\n\nData from Gleditsch, J. M., & Sperry, J. H. (2020). *Ecology and Evolution*, 10(21), 12157-12169.\n\n## Describing location and spread of numerical data\n\n::: columns\n::: {.column width=\"33%\"}\nJapanese white-eye\n\n![](/img/Japanese_White-eye.jpg){width=\"100%\"}\n:::\n\n::: {.column width=\"33%\"}\nred-whiskered bulbul\n\n![](/img/Pycnonotus_jocosus.jpg){width=\"100%\"}\n:::\n\n::: {.column width=\"33%\"}\nwhite-rumped shama\n\n![](/img/wrshama.jpg){width=\"100%\"}\n:::\n:::\n\nImages from Wikipedia\n\n## Describing location and spread of numerical data\n\n**the Mean describes location**\n\n| Descriptor | Parameter | Estimate | Units |\n|------------|-----------|----------|-------|\n| mean | $\\mu$ | $\\bar{Y}$ | measurement unit (e.g. cm, seconds, etc.) |\n\nNotes:\n\n- $\\mu$ is Greek letter pronounced like \"mew\"\n- $\\bar{Y}$ pronounced like \"Y bar\"\n\n## [Sample mean]{.alert}\n\nIn words:\n\n> The [sample mean]{.alert} is the sum of all the observations in a sample divided by $n$, the number of observations\n\nIn math:\n\n$$\\bar{Y} = \\frac{\\sum_{i = 1}^{n} Y_i}{n}$$\n\n## [Sample mean]{.alert}\n\n\n::: {.cell}\n\n:::\n\n\nA subset of 8 white-rumped shama beak length measurements\n\n::: columns\n::: {.column width=\"60%\"}\n![](/img/wrshama.jpg){width=\"65%\"}\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Beak lengths in mm|\n|------------------:|\n|               10.8|\n|                9.2|\n|               12.0|\n|               11.4|\n|               12.1|\n|               10.6|\n|               10.6|\n|               11.6|\n\n\n:::\n:::\n\n:::\n:::\n\nData from Gleditsch, J. M., & Sperry, J. H. (2020). *Ecology and Evolution*, 10(21), 12157-12169.\n\n## [Sample mean]{.alert}\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.pause-think}\n- What is $n$?\n- What is $\\sum_{i = 1}^{n} Y_i$?\n- What is $\\bar{Y}$?\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|  i| $Y_i$|\n|--:|-----:|\n|  1|  10.8|\n|  2|   9.2|\n|  3|  12.0|\n|  4|  11.4|\n|  5|  12.1|\n|  6|  10.6|\n|  7|  10.6|\n|  8|  11.6|\n\n\n:::\n:::\n\n:::\n:::\n\n## Describing location and spread of numerical data\n\n**the Standard Deviation describes spread**\n\n| Descriptor | Parameter | Estimate | Units |\n|------------|-----------|----------|-------|\n| mean | $\\mu$ | $\\bar{Y}$ | measurement unit |\n| standard deviation | $\\sigma$ | $s$ | measurement unit |\n\nNotes:\n\n- $\\sigma$ (\"sig-ma\") is Greek letter \"s\"\n\n## [Sample standard deviation]{.alert}\n\nIn words:\n\n> The [standard deviation]{.alert} is a common measure of the spread of data. It indicates how far the different measurements are (on average) from the mean.\n\nIn math:\n\n$$\n\\begin{aligned}\ns^2 &= \\frac{\\sum_{i = 1}^{n} (Y_i - \\bar{Y})^2}{n - 1} \\\\\ns &= \\sqrt{s^2}\n\\end{aligned}\n$$\n\n$s^2$ is the sample variance\n\nTake square root to get standard deviation: $\\sqrt{s^2} = s$\n\n## [Sample standard deviation]{.alert}\n\n**FAQ**\n\nQ1: Why does the sum of squared deviations ($\\sum_{i = 1}^{n} (Y_i - \\bar{Y})^2$) appear in the numerator?\n\nA1: Negative and positive deviations have the same effect on average deviation. For example, suppose $\\bar{Y} = 0$:\n\n$$(1 - 0) ^ 2 = (1) ^ 2 = 1$$\n$$(-1 - 0) ^ 2 = (-1) ^ 2 = 1$$\n\n## [Sample standard deviation]{.alert}\n\n**FAQ**\n\nQ2: Why use the sum of squared deviations rather than absolute deviations?\n\nA2: The squared values turn out to have better statistical properties than absolute values.\n\n## [Sample standard deviation]{.alert}\n\n**FAQ**\n\nQ3: Why is it divided by $n-1$ rather than $n$?\n\nA3: Dividing by $n$ is [biased]{.alert} and *underestimates* the population standard deviation. Matters most when $n$ is small.\n\n## [Sample standard deviation]{.alert}\n\nA subset of 8 white-rumped shama beak length measurements\n\n::: columns\n::: {.column width=\"60%\"}\n![](/img/wrshama.jpg){width=\"65%\"}\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Beak lengths in mm|\n|------------------:|\n|               10.8|\n|                9.2|\n|               12.0|\n|               11.4|\n|               12.1|\n|               10.6|\n|               10.6|\n|               11.6|\n\n\n:::\n:::\n\n:::\n:::\n\nData from Gleditsch, J. M., & Sperry, J. H. (2020). *Ecology and Evolution*, 10(21), 12157-12169.\n\n## [Sample standard deviation]{.alert}\n\n\n::: {.cell}\n\n:::\n\n\nRemember: $\\bar{Y} =$ 11.04 mm\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|$i$     | $Y_i$|Deviations ($Y_i - \\bar{Y}$) |\n|:-------|-----:|:----------------------------|\n|1       |  10.8|10.8 - 11.04 = -0.24         |\n|2       |   9.2|                             |\n|3       |  12.0|                             |\n|4       |  11.4|                             |\n|5       |  12.1|                             |\n|6       |  10.6|                             |\n|7       |  10.6|                             |\n|8       |  11.6|                             |\n|**Sum** |  88.3|                             |\n\n\n:::\n:::\n\n\n## [Sample standard deviation]{.alert}\n\nBy definition, sum of deviations equals 0\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|$i$     | $Y_i$| Deviations ($Y_i - \\bar{Y}$)|\n|:-------|-----:|----------------------------:|\n|1       |  10.8|                        -0.24|\n|2       |   9.2|                        -1.84|\n|3       |  12.0|                         0.96|\n|4       |  11.4|                         0.36|\n|5       |  12.1|                         1.06|\n|6       |  10.6|                        -0.44|\n|7       |  10.6|                        -0.44|\n|8       |  11.6|                         0.56|\n|**Sum** |  88.3|                         0.00|\n\n\n:::\n:::\n\n\n## [Sample standard deviation]{.alert}\n\nSum of squared deviations is always positive\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|$i$     | $Y_i$| Deviations ($Y_i - \\bar{Y}$)|Squared deviations $(Y_i - \\bar{Y})^2$ |\n|:-------|-----:|----------------------------:|:--------------------------------------|\n|1       |  10.8|                        -0.24|$(-0.24)^2$ = 0.0576                   |\n|2       |   9.2|                        -1.84|                                       |\n|3       |  12.0|                         0.96|                                       |\n|4       |  11.4|                         0.36|                                       |\n|5       |  12.1|                         1.06|                                       |\n|6       |  10.6|                        -0.44|                                       |\n|7       |  10.6|                        -0.44|                                       |\n|8       |  11.6|                         0.56|                                       |\n|**Sum** |  88.3|                         0.00|                                       |\n\n\n:::\n:::\n\n\n## [Sample standard deviation]{.alert}\n\nSum of squared deviations is always positive\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|$i$     | $Y_i$| Deviations ($Y_i - \\bar{Y}$)| Squared deviations $(Y_i - \\bar{Y})^2$|\n|:-------|-----:|----------------------------:|--------------------------------------:|\n|1       |  10.8|                        -0.24|                                 0.0576|\n|2       |   9.2|                        -1.84|                                 3.3856|\n|3       |  12.0|                         0.96|                                 0.9216|\n|4       |  11.4|                         0.36|                                 0.1296|\n|5       |  12.1|                         1.06|                                 1.1236|\n|6       |  10.6|                        -0.44|                                 0.1936|\n|7       |  10.6|                        -0.44|                                 0.1936|\n|8       |  11.6|                         0.56|                                 0.3136|\n|**Sum** |  88.3|                         0.00|                                 6.3188|\n\n\n:::\n:::\n\n\n## [Sample standard deviation]{.alert}\n\n$$s^2 = \\frac{\\sum_{i = 1}^{n} (Y_i - \\bar{Y})^2}{n - 1} = \\frac{6.3188}{7} = 0.9027~\\mathrm{mm}^2$$\n\n::: {.cell}\n\n:::\n\n\n$$s = \\sqrt{0.9027} = 0.9501~\\mathrm{mm}$$\n\nThe standard deviation has the same units as the measurements (mm in this case), so you can describe the departure from the mean in a consistent way.\n\n\"Almost 95% of data typically fall within two standard deviations of the mean\"\n\n## Describing location and spread of numerical data\n\n**Coefficient of Variation is standard deviation as a percentage of the mean**\n\n| Descriptor | Parameter | Estimate | Units |\n|------------|-----------|----------|-------|\n| mean | $\\mu$ | $\\bar{Y}$ | measurement unit |\n| standard deviation | $\\sigma$ | $s$ | measurement unit |\n| variance | $\\sigma^2$ | $s$ | measurement unit$^2$ |\n| coefficient of variation | $\\sigma/\\mu \\times 100\\%$ | CV | percent (%) |\n\nNotes:\n\n- CV is useful for comparing data with different measurement units\n\n## [Coefficient of variation]{.alert}\n\nIn words:\n\n> The [coefficient of variation]{.alert} is the standard deviation expressed as a percentage of the mean\n\nIn math:\n\n$$\\mathrm{CV} = \\frac{s}{\\bar{Y}} \\times 100\\%$$\n\n## [Coefficient of variation]{.alert}\n\nA subset of 8 white-rumped shama beak length measurements\n\n::: columns\n::: {.column width=\"60%\"}\n![](/img/wrshama.jpg){width=\"65%\"}\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Beak lengths in mm|\n|------------------:|\n|               10.8|\n|                9.2|\n|               12.0|\n|               11.4|\n|               12.1|\n|               10.6|\n|               10.6|\n|               11.6|\n\n\n:::\n:::\n\n:::\n:::\n\nData from Gleditsch, J. M., & Sperry, J. H. (2020). *Ecology and Evolution*, 10(21), 12157-12169.\n\n## [Coefficient of variation]{.alert}\n\n$$\\mathrm{CV} = \\frac{s}{\\bar{Y}} \\times 100\\% = \\frac{0.9501}{11.04} \\times 100\\% = 8.61 \\%$$\n\n## Describing location and spread of numerical data\n\n- Rank species by mean beak length by eye\n- Rank species by standard deviation beak length by eye\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](02-describing-data-slides_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=384}\n:::\n:::\n\n\n## Describing location and spread of numerical data\n\n- Rank species by mean beak length by eye\n- Rank species by standard deviation beak length by eye\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Species              | $\\bar{Y}$|  $s$|CV    |\n|:--------------------|---------:|----:|:-----|\n|Japanese white-eye   |      7.76| 0.45|5.74% |\n|red-whiskered bulbul |      8.97| 0.57|6.35% |\n|white-rumped shama   |     11.09| 0.83|7.44% |\n\n\n:::\n:::\n\n\nNote: statistics for larger data set (not subset of 8)\n\nThe mean and the spread increase together. This is common for morphological data.\n\n## Describing location and spread of numerical data\n\n Descriptor | Parameter | Estimate | Units\n------------|-----------|----------|-------\n median     | Median    | $M$      | measurement unit\n\nNotes:\n\n- \"[median]{.alert} is the middle observation in a set of data\"\n\n## [Median]{.alert}\n\nIf $n$ is *odd*:\n\n$$\\text{Median} = Y_{([n+1]/2)}$$\nIf $n$ is *even*:\n\n$$\\text{Median} = [Y_{(n/2)} + Y_{(n/2+1)}]/2$$\n\n## Median\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-describing-data-slides_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n$$n = 8$$\n\n$$\\text{Median} = \\frac{Y_4 + Y_5}{2} = \\frac{10.8 + 11.4}{2} = 11.10~\\text{mm}$$\n\n## Describing location and spread of numerical data\n\n Descriptor | Parameter | Estimate | Units\n------------|-----------|----------|-------\n median     | Median    | $M$      | measurement unit\n interquartile range | Interquartile range    | $IQR$      | measurement unit\n\nNotes:\n\n- \"[*IQR*]{.alert} is the difference between the third and first quartiles of the data. It is the span of the middle 50% of the data.\"\n\n## Interquartile range\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-describing-data-slides_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n$$j = 0.25 n = 0.25 \\times 8 = 2$$\n\n$$\\text{First quartile} = \\frac{Y_2 + Y_3}{2} = \\frac{10.6 + 10.6}{2} = 10.60~\\text{mm}$$\n\n## Interquartile range\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-describing-data-slides_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n\n$$k = 0.75 n = 0.75 \\times 8 = 6$$\n\n$$\\text{Third quartile} = \\frac{Y_{6} + Y_{7}}{2} = \\frac{11.6 + 12}{2} = 11.80~\\text{mm}$$\n\n## Interquartile range\n\n\n::: {.cell}\n\n:::\n\n\n$$\\text{Interquartile range} = \\text{Third quartile} - \\text{First quartile} = 1.20~\\text{mm}$$\n\n$$\\mathit{IQR} = 11.80 - 10.60 = 1.20~\\text{mm}$$\n\n## 3. Describe categorical variables using the [proportion]{.alert}\n\n Descriptor | Parameter | Estimate | Units\n------------|-----------|----------|-------\n proportion     | proportion    | $\\hat{p}$      | probability\n\nNotes:\n\n- the [sample proportion]{.alert} is similar to the [sample mean]{.alert}\n\n## [Sample proportion]{.alert}\n\nIn words:\n\n> The [sample proportion]{.alert} is a measure of the **location** of categorical data. It indicates how frequently a specific category is found in the data.\n\nIn math:\n\n$$\n\\hat{p} = \\frac{N_{[Y = \\text{category}]}}{n}\n$$\n\n## [Sample proportion]{.alert}\n\nHeads or tails?\n\n`H T T T H H T H T T`\n\n![](/img/2023-american-women-quarters-coin-edith-kanakaole-uncirculated-reverse-768x768.jpg)\n\n## [Sample proportion]{.alert}\n\nHeads or tails?\n\n`H T T T H H T H T T`\n\n$$\nN_{[Y = \\text{tails}]} = 6\n$$\n\n$$\nn = 10\n$$\n$$\n\\hat{p}_\\text{tails} = 0.6\n$$\n\n## Edith Kanakaʻole\n\n::: columns\n::: {.column width=\"40%\"}\n![](/img/Edith_Kanakaole.jpg){width=\"100%\"}\nsource: kaainamomona.org\n:::\n\n::: {.column width=\"60%\"}\nE hō mai ka ʻike mai luna mai ē\n\nO nā mea huna noʻeau o nā mele ē\n\nE hō mai\n\nE hō mai\n\nE hō mai ē\n:::\n:::\n\n## 4. Know when to use different descriptive statistics\n\nWhen data are roughly symmetrical and there are not many extreme values\n\n- mean, standard deviation, variance are commonly used\n- CV if you want to compare values on different scales\n\nWhen data are skewed and/or there are many extreme values\n\n- median tells more about a typical unit in the population and is less sensitive to extreme values\n- IQR is less sensitive to extreme values than standard deviation\n\n## Rounding\n\n* No standard rules\n* For this class, round to 2 decimal places\n",
    "supporting": [
      "02-describing-data-slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}